.travis.yml
pkg/operator/start_test.go

we should see green travis on this.

prove travis

---

manifests/v3.11.0/kube-apiserver/defaultconfig.yaml
manifests/v3.11.0/kube-apiserver/deployment.yaml
pkg/operator/sync_kubapiserver_v311_00.go
pkg/operator/v311_00_assets/bindata.go

merge after https://github.com/openshift/origin/pull/20897
/assign @sttts

update to use structured config

---

bindata/bootkube/manifests/kube-apiserver-daemonset.yaml

fix lock path in daemonset

---

bindata/v3.11.0/kube-apiserver/deployment.yaml
manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
pkg/operator/v311_00_assets/bindata.go

/assign @abhinavdahiya @mfojtik

tolerate any taint

---

pkg/test/assets_test.go

Add basic yaml linting test

---

pkg/operator/observe_config.go
pkg/operator/starter.go

react to changes in format in https://github.com/openshift/installer/pull/431

read etcd endpoint information

---

pkg/operator/observe_config.go

tested congruent change in openshift.  Tagging so @mfojtik and @sttts have good levels in the morning to fail with.

use correct slice setting func

---

bindata/bootkube/manifests/kube-apiserver-daemonset.yaml

Fixes apiserver to come up on master nodes.

render: add var-lock init container also to phase 2

---

Dockerfile-origin-release
Makefile

`DOCKER_ORG=sttts make origin-release`

Makefile: add origin-release target

---

hack/lib/Dockerfile-origin-release

Somehow missed this change from @mfojtik's branch.

origin-release: speed-up jq install

---

pkg/operator/starter.go

This starts us reporting status to the CVO.

wire in ClusterOperator status

---

pkg/operator/installer_controller_v311_00.go
pkg/operator/nodeController.go
pkg/operator/starter.go

fixes comments from previous pull
/assign @sttts

comments and fixes

---

bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml

@sttts I think this is stopping me from getting my cluster up

remove file locking

---

glide.lock
pkg/operator/observe_config.go
pkg/operator/observe_config_test.go
pkg/operator/starter.go
vendor/github.com/davecgh/go-spew/.travis.yml
vendor/github.com/davecgh/go-spew/LICENSE
vendor/github.com/davecgh/go-spew/README.md
vendor/github.com/davecgh/go-spew/spew/bypass.go
vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
vendor/github.com/davecgh/go-spew/spew/dump.go
vendor/github.com/davecgh/go-spew/spew/dump_test.go
vendor/github.com/davecgh/go-spew/spew/dumpcgo_test.go
vendor/github.com/davecgh/go-spew/spew/format.go
vendor/github.com/davecgh/go-spew/spew/format_test.go
vendor/github.com/davecgh/go-spew/spew/internal_test.go
vendor/github.com/davecgh/go-spew/spew/internalunsafe_test.go
vendor/github.com/ghodss/yaml/.travis.yml
vendor/github.com/ghodss/yaml/README.md
vendor/github.com/ghodss/yaml/fields.go
vendor/github.com/ghodss/yaml/yaml.go
vendor/github.com/ghodss/yaml/yaml_go110.go
vendor/github.com/ghodss/yaml/yaml_go110_test.go
vendor/github.com/ghodss/yaml/yaml_test.go
vendor/github.com/golang/glog/README
vendor/github.com/golang/glog/glog.go
vendor/github.com/openshift/api/config/v1/register.go
vendor/github.com/openshift/client-go/glide.lock

Rebase of pull request https://github.com/openshift/cluster-kube-apiserver-operator/pull/101.
TODO: add some unit tests.

observe imagePolicyConfig/internalRegistryHostname

---

bindata/v3.11.0/kube-apiserver/pod.yaml
pkg/operator/v311_00_assets/bindata.go

Add probes that matches 3.11.x probes. Next step is to update the installer to wait for the pods to be ready.
/cc @sttts 
/cc @deads2k

add liveness and readiness probes to static pod

---

bindata/v3.11.0/kube-apiserver/pod.yaml
pkg/operator/v311_00_assets/bindata.go

@smarterclayton i'm 85% sure this contributed to the instability for the installer in master on Friday night (the PR that added the probes merged ~2 days ago)
/cc @sttts

update probes port to match the container port

---

pkg/operator/observe_config.go
pkg/operator/observe_config_test.go

When the entire CRD is missing, we can still synchronize most of the config and simply use the last known value for the image config itself.  We need to observe most of the config before this loop starts.
/assign @sanchezl @juanvallejo @sttts 
@sanchezl can you manually verify that if no CRD is present when this process starts, adding the CRD later and setting a value is properly observed?  If not, please add a unit test showing it breaking and find a way to fix it.
@bparees note the structural change

handle case of missing image.config.openshift.io type definition

---

glide.lock
vendor/github.com/openshift/library-go/glide.lock
vendor/github.com/openshift/library-go/pkg/operator/status/controller.go

update library-go for status

---

pkg/operator/configobservation/etcd/observe_etcd.go

[WIP] until pull https://github.com/openshift/installer/pull/694 is merged.

use host-etcd service endpoints

---

pkg/operator/configobservation/network/observe_network.go

Fixes https://github.com/openshift/installer/pull/712

network-observer: set serviceSubnet in apiserver config

---

bindata/v3.11.0/kube-apiserver/installer-pod.yaml
bindata/v3.11.0/kube-apiserver/pod.yaml
pkg/operator/v311_00_assets/bindata.go

/cc @aveshagarwal 
/cc @deads2k

make static pods node critical priority

---

glide.lock
vendor/github.com/openshift/library-go/pkg/operator/resource/resourcehash/as_configmap.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller_test.go

this fixes static pod status reproting

fix status reporting

---

manifests/0000_10_cluster-kube-apiserver-operator_07_clusteroperator.yaml

Adding this resource should give the CVO visibility into whether our component is working or not.
/assign @sttts

add clusteroperator resource to CVO payload

---

manifests/0000_10_cluster-kube-apiserver-operator_07_clusteroperator.yaml

Reverts openshift/cluster-kube-apiserver-operator#163
A different option.
@smarterclayton

Revert "add clusteroperator resource to CVO payload"

---

pkg/operator/resourcesynccontroller/interfaces.go
pkg/operator/resourcesynccontroller/resourcesync_controller.go
pkg/operator/resourcesynccontroller/resourcesync_controller_test.go
pkg/operator/starter.go
pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_v311_00.go

This needs unit tests, but this is where my head is at.
I hit an unfortunate operator bug related to required secrets, so I'm going to sort that out next.
@mrogers950 @mfojtik

add generic, configurable config sync controller

---

bindata/bootkube/manifests/00_openshift-config-managed-ns.yaml
bindata/bootkube/manifests/00_openshift-kube-apiserver-operator-ns.yaml
bindata/bootkube/manifests/configmap-aggregator-client-ca.yaml
bindata/bootkube/manifests/secret-aggregator-client.yaml
pkg/operator/starter.go

Use the aggregator cert/key pairs from our rotation.

use our cert rotation ability

---

pkg/operator/configobservation/images/observe_images.go

`[]string` and `[]interface{}` are not the same, thus we can't use `reflect.DeepEqual()`. This change gives us string slice, so the check that report events when value changed actually works (instead of spamming the server right now).
/cc @bparees 
/cc @sttts

images: fix image observer event reporting

---

bindata/v3.11.0/kube-apiserver/pod.yaml
manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
pkg/operator/v311_00_assets/bindata.go

@deads2k @smarterclayton @derekwaynecarr

set cpu request on kube-apiserver and operator

---

manifests/0000_10_kube-apiserver-operator_06_deployment.yaml

explicitly list metrics port as first containerPort

---

pkg/operator/targetconfigcontroller/target_config_reconciler.go

adds a commit on top of https://github.com/openshift/cluster-kube-apiserver-operator/pull/206 to configure glog

 allow configuring log level of operand

---

glide.lock
pkg/cmd/render/render.go
vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
vendor/github.com/openshift/library-go/pkg/operator/status/status_controller_test.go

proof that https://github.com/openshift/library-go/pull/258 works.
/hold

Simplify conditions

---

bindata/bootkube/manifests/configmap-initial-kube-apiserver-admin-kubeconfig-client-ca.yaml
bindata/bootkube/manifests/configmap-initial-kubelet-serving-ca.yaml
glide.lock
glide.yaml
manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
pkg/operator/certrotationcontroller/certrotationcontroller.go
pkg/operator/certrotationcontroller/dynamic_serving.go
pkg/operator/certrotationcontroller/loadbalancer.go
pkg/operator/certrotationcontroller/servicehostname.go
pkg/operator/configobservation/network/observe_network_test.go
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
vendor/github.com/apparentlymart/go-cidr/.travis.yml
vendor/github.com/apparentlymart/go-cidr/LICENSE
vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
vendor/github.com/apparentlymart/go-cidr/cidr/cidr_test.go
vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
vendor/github.com/apparentlymart/go-cidr/go.mod
vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/target_test.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go

proof of https://github.com/openshift/library-go/pull/270
/hold
illegal fake bump
/assign @sttts

Dynamically set hostnames

---

bindata/bootkube/manifests/configmap-initial-kubelet-client-ca.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

kubelets have clients signed by this short lived cert

trust the new initial kubelet client CA

---

bindata/v3.11.0/kube-apiserver/pod.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v311_00_assets/bindata.go

Replacing https://github.com/openshift/cluster-kube-apiserver-operator/pull/284 as he is out.

fix setting loglevel for the operand

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/bootkube/config/config-overrides.yaml
bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml
bindata/bootkube/manifests/configmap-initial-temporary-kube-apiserver-client-ca.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

Requires https://github.com/openshift/installer/pull/1307

use the full client-ca bundle provided by the installer

---

manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

I swear we did this once before...

switch to pull if not present

---

glide.lock
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/revision_controller.go

https://github.com/openshift/library-go/pull/293
https://github.com/openshift/library-go/pull/292

bump(library-go): improve logging of what causes a static pod rollout

---

bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

To mitigate https://github.com/kubernetes/kubernetes/issues/74412
/cc @sttts 
/cc @deads2k 
/cc @tnozicka

defaultconfig: bump http2-max-streams-per-connection to 2000

---

Makefile
README.md

README/Makefile: replace origin-release with oc-adm-release

---

pkg/operator/certrotationcontroller/certrotationcontroller.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1688610
/assign @deads2k @sttts 
For now:
/hold

Bump cert rotation to 30 days

---

pkg/cmd/render/render.go
pkg/operator/certrotationcontroller/certrotationcontroller.go
pkg/operator/starter.go

Add cert-rotation configmap for setting base rotation interval

---

bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

In preparation for 4.1. Lets re-renable local storage
cc @wongma7 @deads2k

enable local volumes

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
pkg/operator/v311_00_assets/bindata.go

Follow-up of https://github.com/openshift/api/pull/258

Fix admission config

---

Dockerfile
Dockerfile.rhel7
glide.lock
manifests/0000_10_kube-apiserver-operator_01_config.crd.yaml
manifests/0000_10_kube-apiserver-operator_01_config.crd.yaml-merge-patch
vendor/github.com/openshift/api/operator/v1/types.go
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/bindata.mk
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/codegen.mk
vendor/github.com/pkg/profile/.travis.yml
vendor/github.com/pkg/profile/profile.go

Follow-up of https://github.com/openshift/api/pull/264.

operator/v1: fix pattern for managementState

---

pkg/cmd/render/render.go

It appears that installer is capable of injecting additional resources using the flow described in https://github.com/openshift/installer/blob/master/docs/user/overview.md#multiple-invocations
thus we don't need to support it in our render command.
/assign @sttts

Revert render changes from 0b686ff00295c382f245b0b4103a566d672498c8

---

glide.lock
glide.yaml
manifests/0000_10_kube-apiserver-operator_03_version-mapping.yaml
manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
vendor/github.com/openshift/library-go/pkg/operator/status/version.go

a version of https://github.com/openshift/cluster-kube-apiserver-operator/pull/369 that *may* not fail sni

upgrade fix

---

glide.lock
glide.yaml
manifests/0000_10_kube-apiserver-operator_03_version-mapping.yaml
manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
vendor/github.com/openshift/library-go/pkg/operator/status/version.go

fixes typo from https://github.com/openshift/cluster-kube-apiserver-operator/pull/366

Report operand version using environment variable set in operator deployment

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/bootkube/config/config-overrides.yaml
bindata/bootkube/manifests/config.apiserver.yaml
bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
pkg/operator/configobservation/apiserver/observe_apiserver.go
pkg/operator/configobservation/apiserver/observe_apiserver_test.go
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
test/e2e/user_certs_test.go

The load balancer has not yet been switched.

use new certs for service network and localhost

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go

Logic code should not hardcode manifest structure.

targetconfig: don't hardcode image replacements

---

pkg/operator/configobservation/auth/auth_metadata.go

This prevents a state where the KAS will fail to honor metadata permanently.
Signed-off-by: Monis Khan <mkhan@redhat.com>

ObserveAuthMetadata: default authentication.spec.type

---

bindata/v3.11.0/kube-apiserver/pod.yaml
pkg/operator/v311_00_assets/bindata.go

oversight when new containers were added.

include logs in pod status

---

test/library/crypto.go

/assign @tnozicka @sttts
Requires https://github.com/openshift/release/pull/3486

Switch openshift/kas-o to go1.11

---

Dockerfile
Dockerfile.rhel7

Switch to go1.11

---

manifests/0000_10_kube-apiserver-operator_01_operator.cr.yaml
pkg/operator/starter.go
pkg/operator/v311_00_assets/bindata.go

Stealing https://github.com/openshift/cluster-kube-apiserver-operator/pull/396 to add a default value for managementState so as to please the CRD validations

use the CVO to create the operator config

---

bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml

remove resource the MCO owns

---

bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
bindata/v3.11.0/kube-apiserver/pod.yaml
pkg/operator/v311_00_assets/bindata.go

Alternative to https://github.com/openshift/cluster-kube-apiserver-operator/pull/411

Increase minimum-shutdown-duration by 35s to 70s

---

test/e2e/user_certs_test.go

https://github.com/openshift/installer/pull/1633 swapped names

switch to internal hostname

---

glide.lock
vendor/github.com/openshift/api/config/v1/types_cluster_version.go
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/operator/v1/types_etcd.go
vendor/github.com/openshift/api/operator/v1/types_serviceca.go
vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/security/v1/generated.proto
vendor/github.com/openshift/api/security/v1/types.go
vendor/github.com/openshift/library-go/cmd/crd-schema-gen/generator/generator.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/int32.go
vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go

emit events for version changes

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/etcd/observe_etcd.go
pkg/operator/configobservation/interfaces.go
pkg/operator/starter.go

After https://github.com/openshift/installer/pull/1665 this should test green.

only watch openshift-etcd for etcd

---

pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/interfaces.go
pkg/operator/configobservation/scheduler/OWNERS
pkg/operator/configobservation/scheduler/observe_scheduler.go
pkg/operator/configobservation/scheduler/observer_scheduler_test.go

DefaultNodeSelector as a back-up for https://github.com/openshift/origin/pull/22554 if we are not able to arrive at conclusion before code freeze.
/cc @sjenning @deads2k

Add a defaultNodeSelector

---

manifests/0000_20_kube-apiserver-operator_06_deployment.yaml

https://github.com/openshift/cluster-kube-controller-manager-operator/pull/241

manifests: bump loglevel of operator to normal

---

pkg/cmd/resourcegraph/resourcegraph.go

adopting certs from the installer simplified our graph.

update simplified graph

---

pkg/recovery/apiserver.go

Make recovery system:admin part of system:masters group

---

pkg/operator/certrotationcontroller/certrotationcontroller.go

Never shorten signers

---

Dockerfile
Dockerfile.rhel7

Switch to go 1.12

---

bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
bindata/v4.1.0/kube-apiserver/pod.yaml
manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
pkg/cmd/render/render.go
pkg/operator/v410_00_assets/bindata.go

Step three of our seven part plan.  See https://github.com/openshift/cluster-kube-apiserver-operator/pull/510 for details

switch to use hyperkube

---

bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml

bindata/bootkube: fix image for http-check-container

---

pkg/operator/targetconfigcontroller/targetconfigcontroller.go

Let's not redeploy in every loop

Bug 1737683: Sort the EnvVar from Proxy string map

---

Makefile
test/e2e-encryption/encryption_test.go

Signed-off-by: Monis Khan <mkhan@redhat.com>
So that I can have real long running disruptive e2e tests for #516

Add stub test-e2e-encryption suite

---

pkg/operator/configobservation/network/observe_network.go
pkg/operator/configobservation/network/observe_network_test.go

Previously, a null externalip policy would allow all external IPs. We shouldn't actually do this. Null policy should mean blocked by default.

Bug 1751841: null externalip policy should be default-deny

---

bindata/v4.1.0/kube-apiserver/pod.yaml
pkg/operator/starter.go
pkg/operator/v410_00_assets/bindata.go

Bug 1753156: Fix the trusted-ca bundle filename

---

pkg/operator/encryption/shared_encryption.go

Signed-off-by: Monis Khan <mkhan@redhat.com>
@sttts

Add shared encryption controllers logic

---

manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml

Bug 1731228: add alert when feature set is set

---

test/e2e-encryption/encryption_test.go
test/library/encryption/assertion.go
test/library/encryption/helpers.go

by checking (encrypted/decrypted) the content of a secret

Improves TestEncryptionTurnOnAndOff and TestEncryptionRotation

---

test/e2e-encryption/encryption_test.go
test/library/encryption/assertion.go
test/library/encryption/helpers.go

by checking (encrypted/decrypted) the content of a secret

Improves TestEncryptionTurnOnAndOff scenario 

---

pkg/operator/configmetrics/configmetrics.go

Reverts openshift/cluster-kube-apiserver-operator#630

Revert "metrics: report the control plane architecture"

---

bindata/v4.1.0/kube-apiserver/pod.yaml
pkg/operator/certrotationcontroller/certrotationcontroller.go
pkg/operator/configobservation/apiserver/observe_apiserver.go
pkg/operator/configobservation/apiserver/observe_apiserver_test.go
pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pkg/operator/v410_00_assets/bindata.go
test/e2e/user_certs_test.go

This will be used by the cert recovery sidecar.

Add 10y localhost-recovery serving cert

---

bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
pkg/operator/v410_00_assets/bindata.go

The latter is the official flag name, the former from our carry patch.

Replace --{minimal-shutdown -> shutdown-delay}-duration

---

Dockerfile.rhel7
go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/getsentry/raven-go/Dockerfile.test
vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk.help.log
vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk.help.log
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/build.mk
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/test-unit.mk
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/golang/verify-update.mk
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-glide.mk
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps.mk
vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
vendor/modules.txt

`verify-deps` comes in https://github.com/openshift/release/pull/6472 but needs this first
/cc @soltysh @mfojtik

Bump: for new library-go with go mod verify-deps

---

Makefile

Add verify-deps target

---

test/e2e/certrotation_test.go

I would have sworn my original PR had this test....

add test for cert rotation type stomping

---

go.mod
go.sum
vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
vendor/modules.txt

bump: openshift/library-go#653

---

pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
pkg/operator/configobservation/auth/auth_serviceaccountissuer_test.go
pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
test/e2e/bound_sa_token_test.go

Required for openshift/enhancements#150

Enable changing bound service account token issuer from default

---

manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml

manifests: set caFile for service monitor

---

pkg/operator/configmetrics/configmetrics.go

Like feature set and infrastructure, report whether the core apiserver
knows that it should enable proxy support for HTTP, HTTPS, or has a
trusted CA. This will allow additional information to be alerted on.

Bug 1798609: Report a metric about proxy enablement

---

manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml

/assign @mfojtik @LiliC @s-urbaniak

Bug 1793850: Update UsingDeprecatedAPIExtensionsV1Beta1 alert

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

- update library-go for substitution

update library-go for substitution

---

pkg/operator/configobservation/etcd/observe_etcd.go
pkg/operator/configobservation/etcd/observe_etcd_test.go

No need to connect to localhost twice.

Bug 1810712: use localhost name instead of localhost IPs

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/815
/cc @sttts @soltysh

[release-4.4] Bug 1820258: Fix race for localhost-recovery-client-token snapshotting

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/bindata/bindata.go
vendor/modules.txt

Bug 1813894: Stop using service ca from service account token

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
vendor/modules.txt

* openshift/library-go@a4b1c3e3: factory: add bare informer
* openshift/library-go@b051b252: cloudprovider: add oVirt to list of recognized cloud providers

Bug 1832143: bump(*): vendor update

---

manifests/0000_20_kube-apiserver-operator_00_cr-anyuid.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-hostaccess.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-hostmount-anyuid.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-hostnetwork.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-nonroot.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-privileged.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-restricted.yaml

Bug 1833558: create cluster roles for modiyfing scc-s

---

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go

* `api` endpoints in the openshift-apiserver namespace were not being picked up correctly.
* ipv6 endpoint addresses incorrectly formatted.
* handle storage urls when specified as kube-apiserver args

check-endpoints: missing openshift apiserver service endpoints endpoints

---

pkg/cmd/checkendpoints/controller/connection_checker.go
pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go

This will allow us to have one podendpointconnectivity check for each kas-on-node to each oas-on-node instead of one for each oas that is ever created.  This will make it easier to inspect the results.

allow the check-endpoints target and pod to mutate over time

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
vendor/github.com/openshift/library-go/pkg/operator/status/version.go
vendor/github.com/openshift/library-go/test/library/encryption/errors.go
vendor/modules.txt

proof of https://github.com/openshift/library-go/pull/865

bump to delay version update until operand updated

---

Dockerfile.rhel7

Bug 1855575: Bump to go 1.14

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/modules.txt

Pulling in https://github.com/openshift/library-go/pull/871.

Bug 1858763: static-pod-installer: remove deadlock by recreating installers that disappear

---

go.sum
manifests/0000_20_kube-apiserver-operator_00_cr-anyuid.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-hostaccess.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-hostmount-anyuid.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-hostnetwork.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-nonroot.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-privileged.yaml
manifests/0000_20_kube-apiserver-operator_00_cr-restricted.yaml
manifests/0000_20_kube-apiserver-operator_00_namespace.yaml
manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
manifests/0000_20_kube-apiserver-operator_00_scc-privileged.yaml
manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
manifests/0000_20_kube-apiserver-operator_01_operator.cr.yaml
manifests/0000_20_kube-apiserver-operator_02_service.yaml
manifests/0000_20_kube-apiserver-operator_03_configmap.yaml
manifests/0000_20_kube-apiserver-operator_04_clusterrolebinding.yaml
manifests/0000_20_kube-apiserver-operator_05_serviceaccount.yaml
manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
manifests/0000_90_kube-apiserver-operator_01_prometheusrole.yaml
manifests/0000_90_kube-apiserver-operator_02_prometheusrolebinding.yaml
manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml

This is matches https://github.com/openshift/enhancements/pull/414 and doesn't change existing behavior

bug 1871890: add current profile annotations to CVO manifests

---

go.mod
go.sum
vendor/github.com/openshift/api/go.mod
vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
vendor/github.com/openshift/api/imageregistry/v1/types.go
vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
vendor/github.com/openshift/api/operator/v1/types.go
vendor/github.com/openshift/api/operator/v1/types_network.go
vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
vendor/modules.txt

openshift/api#736 added restrictions for logLevel values. This PR vendors new openshift/api to get new CRDs.

Bug 1883698: Bug 1883603: Bump openshift/api

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissions.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/modules.txt

Pickup https://github.com/openshift/library-go/pull/918
Works with https://github.com/openshift/cluster-openshift-apiserver-operator/pull/402.

Bug 1876166: need to be able to disable kube-apiserver connectivity checks

---

pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go

This reverts commit 7a1eb382378730ad57fad1046f24bf2e715757b8.

Revert "connectivitycheckcontroller: disable by default"

---

bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
bindata/bootkube/manifests/secret-control-plane-client-signer.yaml
bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
bindata/bootkube/manifests/secret-service-network-serving-signer.yaml

Screen from console:
/assign @sttts

Use 'kubernetes.io/tls' instead of SecretTypeTLS which is not being substituted

---

pkg/operator/configobservation/auth/webhook_authenticator.go

required in order for https://github.com/openshift/cluster-authentication-operator/pull/304 and https://github.com/openshift/oauth-apiserver/pull/9 to work

token webhook auth: set tokenreview API to v1

---

pkg/operator/starter.go
pkg/operator/webhookauthenticatorupgradablecontroller/webhookauthenticatorupgradablecontroller.go
pkg/operator/webhookauthenticatorupgradablecontroller/webhookauthenticatorupgradablecontroller_test.go

Bug 1895959: don't allow upgrades when webhooktokenauthenticators are set

---

bindata/bootkube/config/bootstrap-config-overrides.yaml
bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
pkg/cmd/render/render.go
pkg/cmd/render/render_test.go

/assign @tnozicka
cc @marun 
depends on https://github.com/openshift/installer/pull/4469

Bug 1902059: bootstrap: always wire bound SA keys

---

pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
pkg/operator/configobservation/auth/auth_serviceaccountissuer_test.go

This PR modifies the SA-issuer observer to match how the other observers are behaving to simplify maintenance.
It's a follow-up to https://github.com/openshift/cluster-kube-apiserver-operator/pull/1020, per request in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1020#discussion_r551799962, I like to believe the code flow is easier to follow now, even for me as I was getting lost in the previous form of it.
/assign @sttts

Bug 1906808: follow-up fixes to SA-issuer observer

---

OWNERS

Remove tnozicka and add soltysh to OWNERS

---

pkg/operator/certrotationcontroller/certrotationcontroller.go

This reverts commit e1094f5fffd3f6e74d22d6c4b803e963e8dda171.

Bug 1883790: Revert "force cert rotation every couple days for development: aggregator-client-signer"

---

go.mod
go.sum
pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
vendor/github.com/openshift/library-go/pkg/config/serving/server.go
vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
vendor/modules.txt

Bug 1926867: competing connectivitycheckcontrollers cause pod restarts during upgrades

---

test/e2e/token_inactivity_timeout_test.go

The token inactivity tests would only wait for KAS-o to
start progressing and then would attempt to check KAS
revisions to be stable, but these could have still been
the previous API server revisions.
-----
it's a hypothesis, let's see the number of successful runs

token inactivity e2e: wait for KAS to stop progressing

---

manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
pkg/operator/starter.go

add collection for a thing I embarrassingly forgot

bug 1949306: collect new style counts

---

manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
pkg/operator/starter.go

bug 1955256: stop collecting deprecateapicount

---

pkg/operator/configobservation/auth/webhook_authenticator.go

Reverts openshift/cluster-kube-apiserver-operator#1129
sorry for not setting the hold, we decided to go with documentation instead.
/cc @stlaz

Bug 1967090: Revert webhookauth observer: set cache TTL to 30s

---

go.mod
go.sum
manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
vendor/modules.txt

I am not sure this will work but I at least want to see it fail and I don't have a cluster handy.

 Bug 1946479: inject SA tokens as projected volumes to KAS install and prune pods

---

pkg/operator/configobservation/apiserver/observe_termination_duration.go
pkg/operator/configobservation/apiserver/observe_termination_duration_test.go

fixes https://issues.redhat.com/browse/API-1283

reduces shutdown-delay-duration to 0s for SNO

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/k8s.io/client-go/restmapper/category_expansion.go
vendor/k8s.io/client-go/restmapper/discovery.go
vendor/k8s.io/client-go/restmapper/shortcut.go
vendor/modules.txt

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1979303 and https://bugzilla.redhat.com/show_bug.cgi?id=1982398

Bug 1979303: clear encryption conditions when there is no work to be done

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/monitor.go
vendor/modules.txt

Pick-up https://github.com/openshift/library-go/pull/1172.

Bug 1989633: bump(library-go): staticpod/installer: skip backoff if lastAvailableRevision > targetRevision

---

bindata/assets/config/defaultconfig.yaml

Required https://github.com/openshift/kubernetes/pull/889.

Bug 1994643: enable shutdown-send-retry-after and startup-send-retry-after-until-ready

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
vendor/modules.txt

Signed-off-by: Antonio Ojea <aojea@redhat.com>

Bug 2001856: bump library-go to latest

---

bindata/assets/alerts/kube-apiserver-slos-basic.yaml
bindata/assets/alerts/kube-apiserver-slos-extended.yaml
pkg/operator/starter.go

- split slos alerts & records into basic & extended groups
- skip registering extended slos alerts on SNO

Bug 2004585: prometheus-k8s-0 cpu usage keeps increasing for the first 3 days

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
vendor/modules.txt

Signed-off-by: Antonio Ojea <aojea@redhat.com>

Bug 2003540: bump library-go

---

bindata/assets/alerts/cpu-utilization.yaml
bindata/assets/alerts/kube-apiserver-slos-basic.yaml
bindata/assets/alerts/kube-apiserver-slos-extended.yaml

relates to https://issues.redhat.com/browse/API-1361

reduce alert severity to warning where appropriate

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/modules.txt

Bumping the library-go dependency to the latest. It brings performance improvements in this [PR](https://github.com/openshift/library-go/pull/1235).

Upgrade library-go version

---

bindata/assets/kube-apiserver/pod.yaml

Replaces deprecated annotation with newer replacement.
/assign @soltysh

Bug 2035986: Replace deprecated annotation

---

go.mod
go.sum
manifests/0000_20_kube-apiserver-operator_03_configmap.yaml
manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
pkg/operator/starter.go
vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
vendor/github.com/openshift/library-go/pkg/crypto/missing_san.go
vendor/github.com/openshift/library-go/pkg/operator/metricscontroller/legacy_cn_certs_sync.go
vendor/github.com/openshift/library-go/pkg/operator/metricscontroller/metrics_controller.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
vendor/github.com/prometheus/client_golang/api/client.go
vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
vendor/modules.txt

This introduces a metric controller observing `apiserver_webhooks_x509_missing_san_total` metric as introduced in https://github.com/kubernetes/kubernetes/pull/95396

Bug 2037274: starter: include metrics controller

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/modules.txt

To pick up https://github.com/openshift/library-go/pull/1287

bug 2005901: Sync the library-go

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
vendor/modules.txt

bringing in openshift/library-go#1300

update library-go to get rapid installer pod fixes

---

pkg/operator/starter.go
pkg/operator/webhooksupportabilitycontroller/webhook_supportability_controller.go

This reverts commit e1ac5e21da448a69243eeb66e4aa5432c21232f3, reversing
changes made to ada99bf03208042cf900867443283509ef71f8c6.

Revert pull request 1309

---

bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-hostnetwork-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-nonroot-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-restricted-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_crb-systemauthenticated-scc-restricted-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted-v2.yaml
bindata/bootkube/scc-manifests/gensccroles.sh

Adds more restrictive version of the `restricted` SCC, also adds more restrictive SCC versions to SCCs that were related to `restricted`.
/cc @s-urbaniak 
/cc @deads2k

add more restrictive SCCs to the platform

---

.ci-operator.yaml
Dockerfile.rhel7
go.mod
go.sum

Replaces https://github.com/openshift/cluster-kube-apiserver-operator/pull/1355
/assign @p0lyn0mial

Updating ose-cluster-kube-apiserver-operator images to be consistent with ART

---

bindata/assets/config/defaultconfig.yaml

Bug 2086519: exempt build controller SA from PodSecurity admission

---

bindata/assets/alerts/podsecurity-violations.yaml

Bug 2101444: specify resource=pod for PSa violation alerts

---

bindata/assets/alerts/podsecurity-violations.yaml

Bug 2100155: specify resource=pod for PSa violation alerts

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/audit-policies-cm-scenario-1.yaml
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/multipleCr.yaml
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/oauth.yaml
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
vendor/modules.txt

bump library-go to carry the fix

Bug 2073220: routes/status resources can leak sensitive data

---

bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml

Similar to https://github.com/openshift/cluster-kube-controller-manager-operator/pull/660
Copy-pasting the requests from https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/bindata/assets/kube-apiserver/pod.yaml

bootstrap-kube-apiserver: specify resources.requests

---

bindata/assets/kube-apiserver/apiserver.openshift.io_apirequestcount.yaml
go.mod
go.sum
pkg/operator/startupmonitorreadiness/readiness_checks.go
pkg/test/assets_test.go
vendor/github.com/openshift/library-go/pkg/assets/assets.go
vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
vendor/github.com/openshift/library-go/pkg/operator/render/render.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/OWNERS
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
vendor/modules.txt

This was added to library-go and used in cluster-config-operator, this brings it in for future use here.
/assign @stlaz

OCPBUGS-3985: update for featureset rendering

---

bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml

backporting https://github.com/openshift/cluster-kube-apiserver-operator/pull/1398/commits

OCPBUGS-4299: bootstrap-kube-apiserver: specify resources.requests

---

pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission_test.go
pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion_test.go

Signed-off-by: Vu Dinh <vudinh@outlook.com>

OCPBUGS-272: Remove duplicate find word in error msg for degraded webhook

---

bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml

backporting https://github.com/openshift/cluster-kube-apiserver-operator/pull/1398

OCPBUGS-4301: bootstrap-kube-apiserver: specify resources.requests

---

bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
bindata/bootkube/manifests/secret-control-plane-client-signer.yaml
bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/modules.txt

Backporting https://github.com/openshift/cluster-kube-apiserver-operator/pull/1410

OCPBUGS-4551: guard controller: set an explicit hostname to avoid name collisions

---

bindata/assets/config/defaultconfig.yaml

increase audit log size to contain an entire upgrade+e2e run

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
vendor/modules.txt

OCPBUGS-5345: routes/status resources can leak sensitive data

---

pkg/operator/configobservation/images/OWNERS

Update OWNERS to remove/replace adambkaplan

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/modules.txt

Backporting https://github.com/openshift/cluster-kube-apiserver-operator/pull/1437

OCPBUGS-7369: Guard pod set readiness probe endpoint explicitly

---

bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted-v2.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml

https://issues.redhat.com/browse/STOR-1051
/hold until CSIInlineVolumeAdmission is GA
/cc @openshift/storage

STOR-1051: Allow CSI inline volumes in all SCCs

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/modules.txt

Backporting https://github.com/openshift/cluster-kube-apiserver-operator/pull/1445

OCPBUGS-7756: Guard pod set readiness probe endpoint explicitly

---

bindata/assets/alerts/podsecurity-violations.yaml

backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1435

OCPBUGS-10712: PSA Violation alert: add ocp_namespace label

---

bindata/assets/config/defaultconfig.yaml
pkg/operator/configobservation/auth/podsecurityadmission.go

/assign @openshift/openshift-team-auth

OCPBUGS-10831: pod security: use v1 api

---

bindata/assets/kube-apiserver/pod.yaml

updates probes to match other apiservers and use startup probes which didn't exist when we started.
/assign @vrutkovs

update probes for best practices and consistency

---

pkg/operator/configobservation/apienablement/observe_runtime_config.go

/assign @benluddy
CC @ingvagabund @soltysh

OCPBUGS-17436: Enable DynamicResourceAllocation API in kube-apiserver

---

bindata/assets/config/defaultconfig.yaml
bindata/bootkube/config/bootstrap-config-overrides.yaml
pkg/cmd/render/render.go
pkg/cmd/render/render_test.go
pkg/operator/configobservation/apienablement/observe_runtime_config.go
pkg/operator/configobservation/apienablement/observe_runtime_config_test.go
pkg/operator/configobservation/configobservercontroller/observe_config_controller.go

Change to test has merged: https://github.com/openshift/origin/pull/28214. It should not be sensitive to differences in the set of served APIs anymore.

OCPBUGS-17436: Unrevert 1536 and 1538.

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

Pulling https://github.com/openshift/library-go/pull/1574

OCPBUGS-16794: installerpod: change pod manifest mode to 0600

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
vendor/modules.txt

This PR is a manual cherry-pick of these 3 PRs;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546

[release-4.12] OCPBUGS-19837: Update staticpod file permissions to conform with CIS benchmarks

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
vendor/modules.txt

Bumping library-go after https://github.com/openshift/library-go/pull/1681 was merged

OCPBUGS-30119: certrotation: Bump library-go to latest master

---

go.mod
go.sum
pkg/operator/certrotationcontroller/certrotationcontroller.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
vendor/modules.txt

Cherrypick of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1651 on 4.15

OCPBUGS-30304: cert rotation: Bump library-go to latest master

---

bindata/assets/alerts/cpu-utilization-sno.yaml
bindata/assets/alerts/cpu-utilization.yaml
pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller.go
pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller_test.go
pkg/operator/highcpuusagealertcontroller/testdata/alert_2_cores.yaml
pkg/operator/highcpuusagealertcontroller/testdata/alert_8_cores.yaml
pkg/operator/starter.go
vendor/k8s.io/client-go/dynamic/fake/simple.go
vendor/k8s.io/utils/cpuset/OWNERS
vendor/k8s.io/utils/cpuset/cpuset.go
vendor/modules.txt

Manual backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1680 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1676

[release-4.16]OCPBUGS-35831: add SNO control plane high cpu usage alert

---

bindata/assets/alerts/cpu-utilization-sno.yaml
bindata/assets/alerts/cpu-utilization.yaml
pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller.go
pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller_test.go
pkg/operator/highcpuusagealertcontroller/testdata/alert_2_cores.yaml
pkg/operator/highcpuusagealertcontroller/testdata/alert_8_cores.yaml
pkg/operator/starter.go
vendor/k8s.io/client-go/dynamic/fake/simple.go
vendor/k8s.io/utils/cpuset/OWNERS
vendor/k8s.io/utils/cpuset/cpuset.go
vendor/modules.txt

Manual backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1680 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1676

[release-4.15]OCPBUGS-35832: add SNO control plane high cpu usage alert

---

bindata/assets/alerts/cpu-utilization-sno.yaml
bindata/assets/alerts/cpu-utilization.yaml
pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller.go
pkg/operator/highcpuusagealertcontroller/highcpuusagealert_controller_test.go
pkg/operator/highcpuusagealertcontroller/testdata/alert_2_cores.yaml
pkg/operator/highcpuusagealertcontroller/testdata/alert_8_cores.yaml
pkg/operator/starter.go
vendor/k8s.io/client-go/dynamic/fake/simple.go
vendor/k8s.io/utils/cpuset/OWNERS
vendor/k8s.io/utils/cpuset/cpuset.go
vendor/modules.txt

Manual backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1680 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1676

[release-4.14]OCPBUGS-31354: add SNO control plane high cpu usage alert

---

Dockerfile.rhel7

test with https://github.com/openshift/api/pull/2030

create CRDs from openshift/api

---

go.mod
go.sum
pkg/operator/starter.go
vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
vendor/github.com/openshift/library-go/pkg/operator/unsupportedconfigoverridescontroller/unsupportedconfigoverrides_controller.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
vendor/modules.txt

requires https://github.com/openshift/library-go/pull/1870

API-1835: migrate startup monitor conditon to ssa 

---

go.mod
go.sum
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/modules.txt

Bump library-go to include https://github.com/openshift/library-go/pull/1929

OCPBUGS-48686: bump(library-go)

---

README.md

related to https://github.com/openshift/cluster-kube-apiserver-operator/pull/1814

NO-JIRA: readme: describe mapping between operatorLogLevel and log level

---

pkg/operator/configmetrics/configmetrics.go

This commit adds two new metrics providing the two topology modes, control plane and infrastructure respectively.

MON-4160: operator: add topology metrics

---

pkg/operator/certrotationcontroller/certrotationcontroller.go

Reverts openshift/cluster-kube-apiserver-operator#1759

Revert "OCPBUGS-43777: certrotationcontroller: run tests which runs deployment and creates projects"

---

pkg/operator/starter.go
pkg/operator/targetconfigcontroller/targetconfigcontroller.go

Currently unless the cluster is an SNO, we wait until etcd is HA.
However when installing a TNF cluster with assisted-installer, there is only going to be one CP node until the very end of the installation because TNF clusters only have 2 CP nodes and assisted-installer uses one of the CP nodes as the bootstrap. So in this case we can't wait for etcd to be HA.
We can know if a cluster is TNF based on it's control plane topology is DualReplica, and we can know if the cluster is installed with assisted-installer by checking if the openshift-etcd namespace has the annotation openshift.io/delayed-bootstrap.
Closes [OCPBUGS-58232](https://issues.redhat.com/browse/OCPBUGS-58232)

OCPBUGS-58232: Don't wait for 2 etcd members when the cluster is TNF installed with assisted-installer

---

pkg/operator/configobservation/apiserver/observe_goaway_chance_test.go

Add negative tests of GOAWAY-chance

NO-JIRA: Add negative tests of GOAWAY-chance

---

bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-nested-container.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-restricted-v3.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nested-container.yaml
bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted-v3.yaml

per https://github.com/openshift/enhancements/blob/master/enhancements/kubelet/user-namespaces-support.md#proposal, drawing additional inspiration from https://developers.redhat.com/articles/2024/12/02/enable-nested-containers-openshift-dev-spaces-user-namespaces?source=sso#cluster_configuration

OCPNODE-2559: SCC: add nested-podman and restricted-v3
