openshift/cluster-kube-apiserver-operator

- manifests/v3.11.0/kube-apiserver/defaultconfig.yaml
- manifests/v3.11.0/kube-apiserver/deployment.yaml
- manifests/v3.11.0/kube-apiserver/public-info-role.yaml
- manifests/v3.11.0/kube-apiserver/public-info-rolebinding.yaml
- manifests/v3.11.0/kube-apiserver/public-info.yaml
- pkg/operator/sync_kubapiserver_v311_00.go
- pkg/operator/v311_00_assets/bindata.go
This exposes information the openshift apiserver operator needs.  Technically it works, but it errors when merging configuration because a sparse config doesn't technically require an apiversion and kind.  This produces an interesting/awful hot loop.
The bug is preexisting, so this is still strictly an improvement.
/assign @sttts @mfojtik
> Exposed config

- manifests/v3.11.0/kube-apiserver/svc.yaml
We compare the type on apply. It is defaulted to ClusterIP on the server, but is empty in the operator manifest.
> svc.yaml: set type:ClusterIP to avoid repeated updates

- hack/lib/build/images.sh
Fixes https://github.com/openshift/cluster-kube-apiserver-operator/issues/18
> remove git clean when building images

- manifests/install/operator.yaml
This let's us do 
`oc get coreoperators -oyaml` and see all the core operator resources we have (four at least).
> add category for crd:

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- cmd/cluster-kube-apiserver-operator/render/config.go
- cmd/cluster-kube-apiserver-operator/render/render.go
This allow to parametrize the lock host path which should fix the SELinux issue in cluster up extended test. Argument is defaulted to pre-existing value, only cluster up will likely override this.
> parametrize lock host dir

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
This will allow to pass selinux for bootstrap static pod. The daemonset pods does not need this for some reason... I tested this and it works. It probably can be tweaked further with `seLinuxOptions`.
> make bootstrap apiserver privileged to work around selinux

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
The lock directory might be shared with controller manager, it is better to remove the files we create in apiserver instead of nuking entire directory.
/cc @sttts 
/cc @openshift/sig-master
> use explicit lock path

- pkg/operator/observe_config.go
- pkg/operator/operator.go
- pkg/operator/starter.go
This adds a config loop to observe cluster information about etcd to drive our endpoints.
/assign @mfojtik @sttts 
/cc @juanvallejo 
@abhinavdahiya fyi, the code consuming your endpoints.
> observe etcd urls from endpoint

- bindata/bootkube/manifests/configmap-etcd-serving-ca.yaml
- cmd/cluster-kube-apiserver-operator/render/config.go
- cmd/cluster-kube-apiserver-operator/render/render.go
Replacement of https://github.com/openshift/cluster-kube-apiserver-operator/pull/51 to unblock us and to move the issue into the installer (where it can be resolved one way or the other).
> render: make etcd-serving-ca customizable

- cmd/cluster-kube-apiserver-operator/render/render.go
This was added by accident. But there is no need for an addition override file. This was only intended for further customization of the config through the installer.
> render: remove --config-override-file default

- manifests/image-references
```
$ oc get is origin-v4.0-20181012001457 -o yaml | grep -B5 "tag: hyperkube"
- items:
- created: 2018-10-12T00:14:57Z
dockerImageReference: docker-registry.default.svc:5000/openshift/origin-v4.0-20181012001457@sha256:d02876d2764600ced0124d9fec8b346c547d3e8334acb66db99f14ed9de630b0
generation: 1
image: sha256:d02876d2764600ced0124d9fec8b346c547d3e8334acb66db99f14ed9de630b0
tag: hyperkube
$ oc get is origin-v4.0-20181012001457 -o yaml | grep -B5 "tag: hypershift"
- items:
- created: 2018-10-12T00:14:57Z
dockerImageReference: docker-registry.default.svc:5000/openshift/origin-v4.0-20181012001457@sha256:492237def6e4b5db4f95838240d493b093fa13c84b77dac82ed8396b26eb67ed
generation: 1
image: sha256:492237def6e4b5db4f95838240d493b093fa13c84b77dac82ed8396b26eb67ed
tag: hypershift
```
In my 4.0 …
> manifests: fix image name

- cmd/cluster-kube-apiserver-operator/render/render.go
https://github.com/openshift/cluster-kube-apiserver-operator/pull/69 with deprecation instead of changing the flag. Allow us to fix installer and remove deprecated flag afterwards.
> render: pluralize --config-overrides-file

- bindata/bootkube/config/config-overrides.yaml
- bindata/bootkube/manifests/daemonset-kube-apiserver.yaml
- bindata/bootkube/manifests/kube-system-configmap-aggregator-client-ca.yaml
- bindata/bootkube/manifests/kube-system-configmap-client-ca.yaml
- bindata/bootkube/manifests/kube-system-configmap-etcd-serving-ca.yaml
- bindata/bootkube/manifests/kube-system-configmap-kube-apiserver-config.yaml
- bindata/bootkube/manifests/kube-system-configmap-kubelet-serving-ca.yaml
- bindata/bootkube/manifests/kube-system-configmap-sa-token-signing-certs.yaml
- bindata/bootkube/manifests/kube-system-secret-aggregator-client.yaml
- bindata/bootkube/manifests/kube-system-secret-etcd-client.yaml
- bindata/bootkube/manifests/kube-system-secret-kubelet-client.yaml
- bindata/bootkube/manifests/kube-system-secret-serving-cert.yaml
Copy the secrets into `kube-system` namespace for the bootkube daemonset and change the daemonset to use them instead of relying on hostPaths, which does not exists on the master nodes.
/cc @deads2k 
/cc @sttts
> manifests: provide kube-system configs and secrets

- bindata/bootkube/manifests/configmap-kube-apiserver-config.yaml
- bindata/v3.11.0/kube-apiserver/cm.yaml
- bindata/v3.11.0/kube-apiserver/deployment.yaml
- pkg/operator/v311_00_assets/bindata.go
We should use the full component name to be consistent.
Moreover, the config from the render step is not used.
> Unify kube-apiserver-config name

- bindata/bootkube/manifests/cluster-role-binding-kube-apiserver.yaml
- bindata/bootkube/manifests/cluster-role-kube-apiserver.yaml
This fixes (together with the correct empty kubelet CA in the apiserver config) the use of `kubectl logs`.
> render: add rbac rules for proxy/logs from apiserver

- cmd/cluster-kube-apiserver-operator/main.go
- pkg/cmd/installer/cmd.go
- pkg/cmd/installer/cmd_test.go
Adds a simple installer command that takes content prefixes and a deployment ID, then fluffs them all up on disk and smashes the pod content into place.
/assign @sttts
> add simple installer

- pkg/operator/observe_config.go
- pkg/operator/observe_config_test.go
- pkg/operator/starter.go
Enables the cluster-kube-apiserver-operator to receive notifications of changes to the  `cluster-config-v1` ConfigMap in the `kube-system` namespace, from which some CIDRs are extracted, i.e:
```yaml
data:
install-config:
networking:
podCIDR: 10.2.0.0/16
serviceCIDR: 10.3.0.0/16
```
Adds the discovered CIDRs to the `restrictedCIDRs` array to the cluster kube apiserver's config. e.g.:
```yaml
admissionPluginConfig:
openshift.io/RestrictedEndpointsAdmission:
configuration:
restrictedCIDRs:
- 10.3.0.0/16 # ServiceCIDR
- 10.2.0.0/16 # ClusterCIDR
```
Resolves #50
> sync restrictedCIDRs with install-config

- bindata/v3.11.0/kube-apiserver/installer-pod.yaml
- pkg/operator/deployment_controller_v311_00.go
- pkg/operator/installer_controller.go
- pkg/operator/installer_controller_v311_00.go
- pkg/operator/nodeController.go
- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
- pkg/operator/target_config_reconciler_v311_00.go
- pkg/operator/v311_00_assets/bindata.go
This adds one loop for the installerController and another loop to maintain the individual targetKubeletStatus for nodes as they come and go.  The pod itself fails to run (image problems), but it's a strong start.
```
containers:
- args:
- -v=4
- -deployment-id=1
- -namespace="openshift-kube-apiserver"
- -pod="kube-apiserver-pod"
- -resource-dir="/etc/kubernetes/static-pod-resources"
- -pod-manifest-dir="/etc/kubernetes/manifests"
- -configmaps="deployment-kube-apiserver-config-1"
- -configmaps="aggregator-client-ca-1"
- -configmaps="client-ca-1"
- -configmaps="etcd-serving-ca-1"
- -configmaps="kubelet-serving-ca-1"
- -configmaps="sa-token-signing-certs-1"
- -secrets="aggregator-client-1"
- -secrets="etcd-client-1"
- -secrets="kubelet-client-1"
- -secrets="serving-cert-1"
command:
- …
```
> create installer loop

- hack/lib/Dockerfile-origin-release
This is helpful to notice errors in the origin-release creation early.
> Makefile: print what origin-release target actually does

- pkg/operator/observe_config.go
- pkg/operator/observe_config_test.go
Updates the Failed condition after syncing the observed config.
All needed configs are required for this operator, so previously observed values are retained when a configuration key is missing or unreadable.
Failed condition is triggered (status=true) when a problem is detected, and cleared(status=false) if reading the config is successful.
> provide config observation operator status 

- Dockerfile-origin-release
- Makefile
The Dockerfile was accidently removed when moving to the common build system.
> Repair origin-release Makefile target

- Dockerfile
- cmd/cluster-kube-apiserver-operator/main.go
1) Before the `--version` flag was not defined and we were not setting the `-ldflag` during the go build. I think it only makes sense to set it when building the images so I updated the Dockerfile. Now:
```
$ docker run --rm  openshift/origin-cluster-kube-apiserver-operator:latest --version
cluster-kube-apiserver-operator version v0.0.0-alpha.0-188-gbf4d1be
```
> fix printing version

- manifests/0000_10_cluster-kube-apiserver-operator_00_namespace.yaml
- manifests/0000_10_cluster-kube-apiserver-operator_03_configmap.yaml
- manifests/0000_10_cluster-kube-apiserver-operator_04_clusterrolebinding.yaml
- manifests/0000_10_cluster-kube-apiserver-operator_05_serviceaccount.yaml
- manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
- pkg/operator/starter.go
Moves our namespace to `openshift-cluster-kube-apiserver-operator` and updates our ClusterOperator to match.
> move to operator specific namespace

- manifests/0000_10_cluster-kube-apiserver-operator_02_service.yaml
- manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
@deads2k @sttts we have the secret volume that we don't mount into container... this is fixing this in addition of metrics service that should be used to serve the operator metrics.
pre-requirement: https://github.com/openshift/library-go/pull/88
/hold
> metrics: add svc for metrics and wire serving certs to deployment

- bindata/bootkube/manifests/configmap-etcd-serving-ca.yaml
- bindata/bootkube/manifests/secret-etcd-client.yaml
- pkg/operator/starter.go
- pkg/operator/target_config_reconciler_v311_00.go
We no longer manage the etcd client cert/key pairs, so instead we copy them from kube-system
/assign @sanchezl @sttts
> copy the etcd CA and client cert/key pair from etcd operator

- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
"crictl ps -a" does not show pod names. So during disaster recovery full names for the containers is helpful.
> Use openshift-kube-apiserve as container name for easier debugging

- bindata/bootkube/manifests/cluster-role-binding-kube-apiserver.yaml
- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/v311_00_assets/bindata.go
The adventure of https://github.com/openshift/installer/pull/703 continues.  These subjects should be `system:` prefixed.  This touches some permissions we apparently need.
/assign @sttts @mfojtik
> system prefix user names for node permissions

- pkg/operator/target_config_reconciler.go
Installing an initial apiserver with broken, incomplete might fail the pivot from bootstrap to operator mode. We should therefore wait until the config has been observed once before installing any static pod to the masters.
This might reduce flakes.
> operator: wait for spec.observedConfig to be filled before installing

- bindata/v3.11.0/kube-apiserver/pod.yaml
- manifests/0000_10_cluster-kube-apiserver-operator_06_deployment.yaml
- pkg/operator/v311_00_assets/bindata.go
One in a series of PRs to set memory requests for all control plane and high memory use components.
We are encountering master instability (https://github.com/openshift/installer/pull/408 https://github.com/openshift/installer/pull/785) as the number of components increase because many components run `BestEffort` giving the scheduler no information on pod resource usage.
On a steady state empty cluster, `kube-apiserver` uses 980Mi.
{pod_name="openshift-kube-apiserver-dev-master-0"} | 979714048
Setting request to `1Gi`.
This component uses the most memory and CPU of any component.  Possible target for future optimization.
@deads2k @sttts  @derekwaynecarr
> add memory request to kube-apiserver and operator pods

- Dockerfile-origin-release
- Makefile
- README.md
Our build scripts are using `IMAGE_ORG` so I've updated the docs and unified all the places to use the same everywhere. 
/assign @sttts
> Use consistently IMAGE_ORG everywhere

- bindata/bootkube/manifests/00_openshift-config-ns.yaml
- bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml
- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
- pkg/operator/target_config_reconciler_v311_00.go
Our client-ca bundle is logically composed of several cabundles maintained by different actors.  We need to add a cluster config option for the cluster-admin to specify one too.
/assign @sttts
> start logical composition of the client ca bundle

- manifests/0000_10_kube-apiserver-operator_07_clusteroperator.yaml
Builds on #177 and adds clusteroperator to the payload.
Wait for this to pass aws a few times.
>  add clusteroperator to payload

- pkg/operator/starter.go
this is scoped down to just adding the related objects so that `openshift-must-gather` will work.
> add related object

- pkg/operator/configobservation/images/OWNERS
- pkg/operator/configobservation/images/observe_images.go
this is spinning events and as the owner of this config, i'm not interested in the event, so i'm removing it rather than investing further time debugging why the comparison is failing.
> remove broken event recording logic

- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
The kube-apiserver shutdown timeout is 60 sec. We give it some more seconds to complete a clean shutdown.
> static-pod: set graceful termination grace period

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
The directory is a host mount, created with 0755.
> audit: log to /var/log/kube-apiserver/audit.log on the host

- bindata/bootkube/manifests/configmap-aggregator-client-ca.yaml
- bindata/bootkube/manifests/configmap-initial-kubelet-serving-ca.yaml
- bindata/bootkube/manifests/configmap-kube-apiserver-client-ca.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
We should be able to delete every namespace except the `openshift-config` namespace and recover.  This clearly separates the initially created certificates from those that are managed.
> make the target namespace removable

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/v311_00_assets/bindata.go
Use endpoints IPs directly instead of service IPs, taking some of the networking logic out of the (stability) equation.
> Enable --enable-aggregator-routing by default

- manifests/0000_10_kube-apiserver-operator_01_config.crd.old.yaml
- manifests/0000_10_kube-apiserver-operator_01_config.crd.yaml
in order to switch to the new api types, we need to update the authentication operator (pull open), but that won't work until the resource it watches actually exists, so this starts that process
> make new openshift/api CRD

- bindata/v3.11.0/kube-apiserver/operator-config.yaml
- manifests/0000_10_kube-apiserver-operator_02_service.yaml
- manifests/0000_10_kube-apiserver-operator_03_configmap.yaml
- manifests/0000_10_kube-apiserver-operator_04_clusterrolebinding.yaml
- manifests/0000_10_kube-apiserver-operator_05_serviceaccount.yaml
- manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
- manifests/0000_10_kube-apiserver-operator_07_clusteroperator.yaml
- manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
- pkg/operator/operatorclient/staticpod_interface.go
- pkg/operator/starter.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/v311_00_assets/bindata.go
1. kubeapiserveroperatorconfig is now called cluster
2. clusteroperator is now kube-apiserver
3. resources in our namespace no longer have the openshift prefix
> tighten kube-apiserver names

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/configobservation/network/observe_network.go
- pkg/operator/configobservation/network/observe_network_test.go
- pkg/operator/v311_00_assets/bindata.go
switch the network admission plugin name.  We'll go after the serialization separately.
> switch network admission plugin name

- bindata/bootkube/manifests/configmap-initial-sa-token-signing-certs.yaml
- bindata/bootkube/manifests/secret-initial-kubelet-client.yaml
- bindata/bootkube/manifests/secret-initial-serving-cert.yaml
- pkg/operator/resourcesynccontroller/resourcesynccontroller.go
The installer provides a set of certificates that we cannot replace, cannot remove, and cannot rotate.  These are the only irreplaceable content in our operator and target namespaces. This pull moves that content into `openshift-config` since we cannot manage it.  In theory, this will make it possible to delete the entire operator and target namespace and recover from it.
/assign @sttts @mfojtik
> move all irreplaceable content to openshift-config

- pkg/operator/configobservation/apiserver/observe_apiserver.go
- pkg/operator/configobservation/apiserver/observe_apiserver_test.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/configobservation/interfaces.go
- pkg/operator/starter.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Building on https://github.com/openshift/cluster-kube-apiserver-operator/pull/230 while @sanchezl is out. 
Original PR description:
* User client-ca bundle cert synced to `user-client-ca` in the operator's namespace. No update to the observed config.
* User serving cert synced to `user-serving-cert` in the operator's namespace. No update to the observed config.
* Up to 10 user SNI/named certs synced to `user-serving-cert-nnn` in the operator's namespace. Updated observed config to pick them up.
* target controller will copy the user certs out of the operator's namespace if found (they are optional).
* target controller added user client ca bundle to combined final bundle.
> Observe apiserver config

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/configobservation/network/observe_network.go
- pkg/operator/configobservation/network/observe_network_test.go
- pkg/operator/v311_00_assets/bindata.go
Admission plugins and their configuration types have been groupified.  We tolerate both at the moment to make this transition, but once we merge this pull we will remove the old configuration.
@openshift/sig-networking fyi
/assign @sttts @mfojtik @soltysh
> update admission configuration for groupification

- pkg/operator/configobservation/apiserver/observe_apiserver.go
- pkg/operator/configobservation/auth/auth_metadata.go
First commit removes log spam from the auth observer and second from the apiserver config observer (when the "cluster" is not found, we produce errors every N seconds, making logs unreadable).
> Fix log spamming by auth and apiserver observer

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/resourcesynccontroller/resourcesynccontroller.go
- pkg/operator/v311_00_assets/bindata.go
This pulls finishes the wiring for requiring proper serving certs from kubelets
@sjenning 
/assign @sttts @mfojtik
> start requiring kubelet trust

- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/starter.go
- pkg/operator/v311_00_assets/bindata.go
We need https://github.com/openshift/installer/pull/1253 to support this transition.
In addition to changing the pod names, this also add revision suffix into pod container name, so it is clear in artifacts which revision the collected logs belonged to.
/hold
> operator: remove openshift prefix from pod name

- pkg/operator/reactionchain/interfaces.go
- pkg/operator/reactionchain/reactionchain.go
This adds a command to the `cluster-kube-apiserver-operator` that explains where resources come from by building a digraph where nodes are resources and edges represent logical flow.  The roots are
1. Payload
2. Installer
3. User
Here is the state we're in today:
> explain where kube-apiserver resources come from

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1666635
When operator management state is set to unknown value (because we miss the CR validation), the target controller should not keep managing but emit warning and do nothing.
> targetconfigcontroller: emit warning when management state is set to unknown value

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/bootkube/config/config-overrides.yaml
- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/targetconfigcontroller/config_restriction.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/v311_00_assets/bindata.go
requires https://github.com/openshift/origin/pull/22054
This removes the oauthConfig and makes it impossible to specify one via our operator.  
@openshift/sig-master
> stop serving oauth config

- bindata/bootkube/manifests/configmap-initial-kubelet-serving-ca.yaml
The kcm bootstrap needs to use the new short lived cert to sign, but the kas needs to honor that first.  This adjusts us to handle it.
> honor both the old and new csr signers until kcm switches

- bindata/bootkube/manifests/configmap-initial-kube-apiserver-admin-kubeconfig-client-ca.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
pulls the admin client-ca.crt from installer and sets it up to be included in the client-ca for our server.
> add trust for new admin kubeconfig client-ca

- bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
- bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
- bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
- glide.lock
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- vendor/github.com/openshift/library-go/pkg/assets/template.go
- vendor/golang.org/x/tools/go/gcexportdata/example_test.go
- vendor/golang.org/x/tools/internal/lsp/cache/view.go
- vendor/golang.org/x/tools/internal/lsp/lsp_test.go
- vendor/golang.org/x/tools/internal/lsp/protocol/text.go
- vendor/golang.org/x/tools/internal/lsp/server.go
This doesn't wire us to serve with these new certs, but it does establish adoption of signing certs so we can rotate in the future.
/assign @sttts 
To make this actually work, we need to turn the list of hostnames into a function and we need to re-sign when it changes.
> adopt signers from installer for rotating serving certs

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/bootkube/config/config-overrides.yaml
- bindata/bootkube/manifests/configmap-initial-aggregator-client-ca.yaml
switches our bootstrapping to the short lived cert from https://github.com/openshift/installer/pull/1232
> switch to new aggregator cert

- bindata/bootkube/manifests/configmap-initial-kube-apiserver-serving-ca.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
We need to provide a cabundle for trusting the kube-apiserver since we're minting certificates.
> provide ca bundle for trusting the kube-apiserver

- bindata/bootkube/manifests/configmap-initial-kubelet-serving-ca.yaml
in order to use the new short-lived CSR, we have to trust it to serve kubelets.
> trust csr signer to serve kubelets

- bindata/bootkube/manifests/configmap-admin-kubeconfig-client-ca.yaml
- bindata/bootkube/manifests/configmap-node-bootstrap-client-ca.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
After this, we should be able switch to the knew admin.kubeconfig file and remove the deprecated one.
> trust the kubeconfig signers from the installer

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/v311_00_assets/bindata.go
The SDN needs some time to converge when endpoints change. This minimal shutdown time delay the actual shutdown (and stop of serving) to avoid that race.
> Set minimal-shutdown-duration to 3s

- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/v311_00_assets/bindata.go
Using init container we can get rid of the bash wrapper in apiserver pod and get rid of ugly string append for setting the log level (and any future extra argument we will need).
/cc @sttts 
/cc @deads2k
> operator: add init container to fix audit permissions

- manifests/0000_10_kube-apiserver-operator_03_version-mapping.yaml
- manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
- manifests/0000_10_kube-apiserver-operator_07_clusteroperator.yaml
- manifests/image-references
based on comments in https://github.com/openshift/cluster-image-registry-operator/pull/219, these keys should function properly with the payload we have today.
> minor fitting to set versions for our operator

- manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
specifies system-cluster-critical priority for operator.
blocks passing smoke tests for ensuring control plane pods always schedule.
see: openshift/origin#22217
> manifests: operator is system-cluster-critical priority

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/starter.go
- pkg/operator/v311_00_assets/bindata.go
since https://github.com/openshift/origin/pull/22229 merged, we can reload most
We need https://github.com/openshift/origin/pull/22239 to reload the aggregator client
/hold
> use dynamic reloading of certs to avoid rolling out new deployment versions

- Makefile
- test/e2e/operator_test.go
- test/library/client.go
An initial structure for running e2e tests.
* Added `./test/library` for library/framework code.
* Added `./test/e2e` for tests.
* Added a make target `test-e2e` intended to be executed by CI. e.g :
```console
$ make test-e2e JUNITFILE=/tmp/artifacts/unit_report.xml
```
* See https://github.com/openshift/release/pull/3000
> initial e2e-operator tests

- pkg/cmd/render/render.go
- pkg/cmd/render/render_test.go
Fix https://jira.coreos.com/browse/CLOUD-357
Remove dependency with cluster api cluster object:
- discoverIPs from network config
- fallback to discover from cluster api object
Also fixes an issue that was shadowing the returned err https://github.com/openshift/cluster-kube-apiserver-operator/pull/351/files#diff-5e45df1052a09901f6732e8a838541ebL206
Once we get this in we need to do the same for the controller manager.
Then we can merge https://github.com/openshift/installer/pull/1449
Then we can remove the fallback to discover from cluster api object
> Remove cluster api dependency

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/v311_00_assets/bindata.go
Rebase of https://github.com/openshift/cluster-kube-apiserver-operator/pull/318.
Necessary to make https://github.com/openshift/installer/pull/1421 effective. 5 seconds is not enough for the ELB to notice an issue and to update, 35s should.
@wking @abhinavdahiya
> Increase minimal-shutdown-duration to 35s to cope with slowly converging SDN

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/v311_00_assets/bindata.go
And update bindata. Why was that not caught through verify?
> audit-policy: exclude /readyz

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/bootkube/config/config-overrides.yaml
- bindata/bootkube/manifests/configmap-csr-controller-ca.yaml
kube-ca shouldn't be used and this switches us to the one the installer wires
> switch to constrained CSR signer for kubelet verification

- test/e2e/operator_test.go
Ensure that OPERAND_IMAGE_VERSION is substituted properly.
See https://github.com/openshift/cluster-kube-apiserver-operator/pull/366
> add test for operand image version

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
Setting deletionGracePeriodSeconds in ObjectMeta is just ignored and never had any effect.
Follow-up TODO: verify that cri-o+kubelet follow this value.
> Set terminationGracePeriodSeconds in pod spec

- bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml
The kube-ca is dead.  This is used to terminate serving certs from the kube-apiserver
requires https://github.com/openshift/installer/pull/1593
> fix the ca-bundle used by MCD

- pkg/operator/certrotationcontroller/certrotationcontroller.go
- pkg/operator/configobservation/apiserver/observe_apiserver.go
- pkg/operator/configobservation/apiserver/observe_apiserver_test.go
- pkg/operator/starter.go
- test/e2e/user_certs_test.go
switch to the specific kube-apiserver serving certs for serving the API.
> use the new installer certs to serve

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/bootkube/manifests/configmap-initial-kube-apiserver-serving-ca.yaml
- bindata/bootkube/manifests/configmap-node-bootstrap-client-ca.yaml
- bindata/bootkube/manifests/secret-initial-serving-cert.yaml
- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/resourcesynccontroller/resourcesynccontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/v311_00_assets/bindata.go
The kube-ca is nearly dead.  We can switch our serving-certs now that the kubelets/MCO are updated.
> remove kube-ca certs from kas-o

- test/e2e/user_certs_test.go
https://github.com/openshift/cluster-kube-apiserver-operator/pull/395 changed the default cert to avoid using kube-ca and still serve a working service IP address.  Somehow it merged by bot (still looking at that).  This should fix HEAD
> update the default cert to match

- test/e2e/user_certs_test.go
Alright, nuclear option.  SNI has to be working in order for us to terminate localhost for controller and scheduler and terminating kubelet load balancer connections.  Something is wrong with detection of completion of progressing.  This disables the naughty test to land other pulls.
> disable user sni check

- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
Speed up starting the kube apiserver container by not running 2 init containers but only run 1 container.
> squash init containers to one

- test/e2e/user_certs_test.go
Re-enable the SNI/Named Certificates test, providing an alternate method of waiting for the configuration to take effect.
> re-enable SNI e2e tests

- pkg/operator/certrotationcontroller/externalloadbalancer.go
- pkg/operator/certrotationcontroller/internalloadbalancer.go
The `.status.apiServerURL` [1] states the this value can be used by components like kubelet on machines, to contact the `apisever` using the infrastructure provider rather than the kubernetes networking.
Therefore, this will be set to `api-int.$cluster_domain` as that is URL that should be used by the LB consumers of apiserver.
currently the external serving cert controller is using this value to generate the certificate, when it should be the one doing the replace magic from [2] and not the internal serving cert controller and which causes wrong certificate generation
when we finally switch to `api-int` [3]:
```console
$ oc get secrets -n openshift-kube-apiserver external-loadbalancer-serving-certkey -oyaml
apiVersion: v1
data:
tls.crt: …
```
> certoperator: fix incorrect use of infrastructure.config.openshift.io API

- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/operatorclient/interfaces.go
- pkg/operator/resourcesynccontroller/resourcesynccontroller.go
No resource we use should be located in kube-system anymore
> switch to relying on etcd info in openshift-config

- bindata/bootkube/manifests/config.apiserver.yaml
- bindata/bootkube/manifests/configmap-admin-kubeconfig-client-ca.yaml
- bindata/bootkube/manifests/configmap-csr-controller-ca.yaml
- bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml
- bindata/bootkube/manifests/configmap-initial-temporary-kube-apiserver-client-ca.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Multiple refactors have led to confusing cruft that has a long life on our clusters.  This removes that we don't use or honor
> remove resources we no longer use

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/bootkube/manifests/configmap-sa-token-signing-certs.yaml
- bindata/bootkube/manifests/secret-initial-kubelet-client.yaml
- bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- pkg/operator/resourcesynccontroller/resourcesynccontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
This removes the final kube-ca cert for real this time.
/hold
holding so that I can check to be sure we successfully collect pod logs
> generate and maintain our own kube-apiserver-to-kubelet-signer

- manifests/0000_10_kube-apiserver-operator_06_deployment.yaml
for upgrades, we need to have deployment strategy recreate on our operators in case they are ever scaled. We don't want to ever get a lease for new and later get a lease for old.
We need a distinct operator container to make install-gather happy at the moment.
@openshift/sig-master
> update deployment for upgrade and install-gather

- bindata/v3.11.0/kube-apiserver/pod.yaml
- pkg/operator/v311_00_assets/bindata.go
So inside apiserver we know which revision we run now for the sake of logging.
> bindata: add STATIC_POD_VERSION variable to kube-apiserver pod

- bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
- bindata/bootkube/manifests/00_openshift-kube-apiserver-operator-ns.yaml
- bindata/v3.11.0/kube-apiserver/ns.yaml
- manifests/0000_10_kube-apiserver-operator_00_namespace.yaml
- pkg/operator/v311_00_assets/bindata.go
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR.
/cc @deads2k @sjenning
> Add node-selector to namespace

- Makefile
- test/e2e/user_certs_test.go
- test/library/cluster_operator.go
The `TestNamedCertificates` e2e test occasionally timeouts waiting for changes to take effect. This PR works around that by:
* looping on the first test until it passes, showing that at least one kube-apiserver is running with the configuration to be tested
* Then looping on each subsequent test until it passes (just in case it takes a couple of tries to hit the updated kube-apiserver).
> fix flaky e2e test

- manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.json
- manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.json
- manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.json
- manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.json
- manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.json
- manifests/0000_20_kube-apiserver-operator_00_scc-privileged.json
- manifests/0000_20_kube-apiserver-operator_00_scc-restricted.json
We now have a CRD for SCC, which means we can initialize this early.
> move SCC initialization to kas-o

- bindata/v3.11.0/kube-apiserver/svc.yaml
- pkg/operator/starter.go
- pkg/operator/v311_00_assets/bindata.go
I can't find where this serving-cert is used, but it creates a dependency on the service-ca which can lead to instability.
> remove dependency on the service-ca from kube-apiserver

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Installing before this was available caused us to use the wrong etcd location, which led to debugging.  This would prevent us from rolling out and give a good message.
Also, we should make this check generic, turns out there's a fair amount to it.
/assign @sttts
> require storage URLs before installing

- manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
As of now, because of infinite tolerations against all the possible taints, we are seeing that operators are not getting evicted from nodes that have NoExecute taint on them. This PR tightens the conditions around which can be pods can be scheduled/evicted. The downside is there is a very good chance that pods would be evicted from nodes that have certain conditions like disk-pressure, memory-pressure, taints added by other controllers(operators) etc. So, please make sure that this change is ok with your operator/operand before merging this PR.
/cc @sjenning @smarterclayton
>  Bug 1705649 : Cluster with halted master did not reschedule operators after 5m of being down

- pkg/cmd/regeneratecerts/regenerate_certificates.go
https://github.com/openshift/cluster-kube-apiserver-operator/pull/469 has fixed the csr-signer certificate format, but it forgot to use the new file
/cc @deads2k @soltysh
> Fix csr-signer location to target namespace

- pkg/operator/certrotationcontroller/externalloadbalancer.go
- pkg/operator/certrotationcontroller/internalloadbalancer.go
Prevent panic that somehow occur during the operator graceful shutdown.
`
Shutting down CertRotation\npanic: runtime error: slice bounds out of range\n\ngoroutine 657 [running]:\ngithub.com/openshift/cluster-kube-apiserver-operator/pkg/operator/certrotationcontroller.(*CertRotationController).syncInternalLoadBalancerHostnames(0xc0001692c0, 0x0, 0x0)\n    /go/src/github.com/openshift/cluster-kube-apiserver-operator/pkg/operator/certrotationcontroller/internalloadbalancer.go:20 +0x254\ngithub.com/openshift/cluster-kube-apiserver-operator/pkg/operator/certrotationcontroller.(*CertRotationController).WaitForReady(0xc0001692c0, 0xc0000b3680)\n    /go/src/github.com/openshift/cluster-kube-apiserver-operator/pkg/operator/certrotationcontroller/certrotationcontroller.go:467 …
> certrotationcontroller: prevent panic when setting loadbalancer hostname

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/v311_00_assets/bindata.go
/assign @smarterclayton @mfojtik @sttts @deads2k @derekwaynecarr 
Not setting this value will cause us to default it from here: https://github.com/openshift/origin/blob/7599337aeefb8314f9b5bb832b42639d4e28ce26/pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go#L58
> Bug 1710293 - Don't explicitly set storagePrefix to use the default value

- bindata/v4.1.0/kube-apiserver/recovery-config.yaml
- pkg/operator/v410_00_assets/bindata.go
Catches up with storage change made here https://github.com/openshift/cluster-kube-apiserver-operator/pull/475
/priority critical-urgent
/cc @openshift/sig-master @derekwaynecarr @smarterclayton
> Bug 1711185 - Remove storage prefix to default to correct one for kube resources in recovery apisever

- bindata/v3.11.0/kube-apiserver/recovery-config.yaml
- pkg/operator/v311_00_assets/bindata.go
Catches up with storage change made here https://github.com/openshift/cluster-kube-apiserver-operator/pull/476
/priority critical-urgent
/cc @openshift/sig-master @derekwaynecarr @smarterclayton
> Bug 1711185 - [4.1] Remove storage prefix to default to correct one for kube resources in recovery apisever

- pkg/operator/configobservation/apiserver/observe_apiserver.go
- pkg/operator/configobservation/apiserver/observe_apiserver_test.go
When specifying a user managed default cert in apiservers/cluster:
```
spec:
servingCerts:
defaultServingCertificate:
name: my-cert-secret
```
The secret is never copied to it final destination, resulting in a crash looping kube-apiserver pod.
> Bug 1711431: user-serving-cert secret not being installed

- bindata/bootkube/manifests/configmap-unsupported-cert-rotation.yaml
The bug to get this reverted for 4.2 is https://bugzilla.redhat.com/show_bug.cgi?id=1716978
This should set base cert rotation for 1m, which means that most certs will be rotated every 15 minutes, with validity for 30 mins. 
/assign @deads2k  @mfojtik
> Set short rotation period

- bindata/bootkube/manifests/configmap-unsupported-cert-rotation.yaml
This reverts commit b36a3f6066282bca0ce874675539e0854996e2fb, #493
This change killed the past eight hours of e2e-aws tests (e.g. [here][1] and [here][2]), so there's already plenty of data to dig through.  Revert to get CI flowing again for everyone else.
[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/320/pull-ci-openshift-machine-api-operator-master-e2e-aws/1118
[2]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22970/pull-ci-openshift-origin-master-e2e-aws/9433
> Revert "Set short rotation period"

- bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/configobservation/network/observe_network.go
- pkg/operator/configobservation/network/observe_network_test.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
- pkg/operator/v410_00_assets/bindata.go
This takes over #491, which fixes admission plugin configuration transmutation, but uncovered a bug in the network observer.
This PR also fixes the network observer.
>  Bug 1716426 : Fix admission plugin configuration

- bindata/v3.11.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/configobservation/network/observe_network.go
- pkg/operator/configobservation/network/observe_network_test.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
- pkg/operator/v311_00_assets/bindata.go
This backports the the admission controller fixes in #494, along with an extra commit that leaves the ExternalIPRanger disabled.
> Bug 1716426: Backport admission controller fixes

- README.md
Update the default config url to a valid location
> docs: Update default config url in Readme file

- bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/v410_00_assets/bindata.go
Even the metadata level is not safe as metadata.name is the secret.
Signed-off-by: Monis Khan <mkhan@redhat.com>
@deads2k
> Bug 1718052: Do not log OAuth tokens in audit logs

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
tldr: we want to move the service monitor creation for the apiserver out of cluster monitoring operator into the operator repos themselves.
/cc @sttts @brancz 
Fixes MON-670
> manifests: add apiserver service monitor

- bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
- bindata/v4.1.0/kube-apiserver/ns.yaml
- pkg/operator/v410_00_assets/bindata.go
Currently, any servicemonitor deployed in the openshift-kube-apiserver namespace
is not being monitored.
This fixes it.
/cc @sttts @brancz
> manifests: monitor openshift-kube-apiserver namespace

- pkg/cmd/render/render.go
We want to use hyperkube instead of hypershift.  To do so in an orderly fashion will take a few steps with pulls to different repos.
`--newImage` allows us to change our image to one with a different binary without breaking functionality at intermediate steps
1. allow `--newImage`
2. installer passes `--image=old` and `--new-image=new`
3. operator render uses `--new-image` only
4. installer passes `--image=new` and `--new-image=new`
5. operator switches back to `--image`
6. installer passes `--image=new`
7. operator removes `--new-image`
> allow --new-image for step 1 of 7

- pkg/cmd/render/render.go
Part 5 of the 7 step plan from https://github.com/openshift/cluster-kube-apiserver-operator/pull/510
> use the new image since the installer is setting it correctly

- pkg/cmd/render/render.go
completes the cruft removal on the seven part plan
> remove temporary image flag for switch images

- pkg/operator/configobservation/apiserver/observe_apiserver.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Based on bug https://bugzilla.redhat.com/show_bug.cgi?id=1720770 , this setting never worked.
This setting is inherently dangerous because we rely on the default serving cert to have critical IPs included in valid names to allow the service network to continue to function.  Customers should instead use the SNI capabilities we have to provide their certificates.
This pull removes our attempt to honor the setting and we will ripple through the API and the docs (https://github.com/openshift/openshift-docs/pull/15642)
/assign @sttts 
@derekwaynecarr we had an accident.
> Bug 1720770: remove broken default serving cert

- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/configobservation/network/observe_network.go
- pkg/operator/configobservation/network/observe_network_test.go
API PR: https://github.com/openshift/api/pull/347
This PR adds support for configuring the ExternalIPRanger admission controller from the new ExternalIPs field on the Network configuration object.
> ConfigObservation: add ExternalIPRanger admission controller 

- pkg/operator/configmetrics/configmetrics.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/starter.go
The infrastructure provider metric summarizes the desired type and
region (if any) to prometheus, based on the desired config. If type
is not recognized it is passed along, if it is empty it is set as
empty.
> Bug 1731232: Report infrastructure provider metric from the operator

- pkg/operator/configmetrics/configmetrics.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/starter.go
A cluster that has specific featureSets configured is blocked from 
upgrading, which should be an alert. Expose a metric from the KAO which
allows the cluster to alert on this state.
> Bug 1731228: Expose feature set field as a metric for alerting

- pkg/operator/configmetrics/configmetrics.go
By convention constant metrics in prometheus use value 1 when "enabled".
Map value 1 to "has cloud provider" for the cluster_infrastructure_provider
metric  and value 1 to "using defaults" for the cluster_feature_set metric.
Also clarify the difference between "None" and empty string for cloud
provider type for future reference.
Follow on to #526 and #527 after playing with queries.
> metrics: Report values to improve querying for core metrics

- pkg/operator/certrotationcontroller/certrotationcontroller.go
It should have been 1 year as is in bootstrap
https://bugzilla.redhat.com/show_bug.cgi?id=1733109
/cc @deads2k 
/cherrypick release-4.1
> Bug 1733109: Fix kube-apiserver-to-kubelet-signer validity

- test/e2e/operator_test.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1699471
When operators hotloop creating new revisions, old revisions get their status stuck `InProgress` which doesn't count them toward the Failed/Succeeded revision limits, allowing revision counts to get very high. This tries to check a couple things:
1. That the revision count isn't higher than the sum of the failed/succeeded limits. This would indicate InProgress revisions (of which there shouldn't ever be more than 1)
2. That revisions aren't being rapidly created, by polling and tracking new revisions created. 30 seconds or so of no new revisions is probably good enough to see that we're not currently hotlooping
3. If 20 revisions have been created, we've got too much
`#2` and `#3` are kind of redundant, so if either one is preferred …
> Revision hotlooping e2e test

- pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
- pkg/operator/featureupgradablecontroller/feature_upgradeable_controller_test.go
- pkg/operator/starter.go
- test/e2e/featuregate_upgradeable_test.go
I'm not excited about this.  I still think it belongs in the CVO, but every release it isn't present is one more release harder it is to enforce later on.
This adds a simple way to force the ugpradeable condition false on featuregate values.
> block upgrades on bad featuregates

- pkg/operator/certrotationtimeupgradeablecontroller/certrotationtime_upgradeable.go
- pkg/operator/certrotationtimeupgradeablecontroller/certrotationtime_upgradeable_test.go
- pkg/operator/starter.go
- test/e2e/certrotationtime_upgradeable_test.go
We named this "unsupported-cert-rotation-config".  This adds logic to give that some teeth.
/assign @enj
> add cert rotate upgrade prevention

- glide.lock
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/configobservation/interfaces.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/default.example.mk.help.log
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/operator.example.mk.help.log
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/images.mk
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/proxy/observe_proxy_test.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/google.golang.org/appengine/capability/capability.go
Adds an observer for the Proxy object, pulls its fields and passes
them to the environment of the deployed kube-apiserver container.
> Start observing the Proxy object

- bindata/v4.1.0/kube-apiserver/recovery-config.yaml
- bindata/v4.1.0/kube-apiserver/recovery-pod.yaml
- manifests/image-references
- pkg/cmd/render/render.go
- pkg/operator/v410_00_assets/bindata.go
- pkg/recovery/apiserver_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1732377
leftovers from https://github.com/openshift/cluster-kube-apiserver-operator/pull/511
/cc @sttts @deads2k
> BUG 1732377: Fix kube-apiserver image in rest of the files to use hypekube

- pkg/operator/configmetrics/configmetrics.go
4.1 clusters do not set infrastructure.status.platformStatus, causing the metric for cluster infrastructure to be empty. If platformstatus is nil, fallback to infrastructure type. A bug has been opened to ensure 4.2 clusters have platformStatus set during upgrade.
The previous PR #531 did not cover this difference and so reported an empty metric.
> Bug 1732945: Fallback to platform type on 4.1 infra metrics

- pkg/operator/certrotationcontroller/certrotationcontroller.go
backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/533
https://bugzilla.redhat.com/show_bug.cgi?id=1733232
/cc @deads2k @mfojtik
> Bug 1733232: Fix kube-apiserver-to-kubelet-signer validity

- bindata/v4.1.0/kube-apiserver/pod.yaml
- bindata/v4.1.0/kube-apiserver/trusted-ca-cm.yaml
- pkg/operator/starter.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/v410_00_assets/bindata.go
Adds the trusted store injection and a watchdog that will restart
the kube-apiserver process on the trusted CA bundle change.
> Inject kube-apiserver pods trust stores with trusted ca bundle

- Makefile
@deads2k 
this PR fixes 'make images' (this is only run locally AFAIK, but was broken nonetheless)
`make images` requires `image name` parameter
> updateMakefile to fix 'make images'

- bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/v410_00_assets/bindata.go
This allows the NO_PROXY setting to only list internal node CIDRs which reduces churn as nodes are added and removed.
I'm not completely sure of all the downstream impacts from this choice.
> only use the internalIP to speak to kubelets

- pkg/cmd/regeneratecerts/regenerate_certificates.go
honor the location change from https://github.com/openshift/cluster-kube-controller-manager-operator/pull/279 for recovery tool.
> update recovery tool location for kcm CSR location change

- pkg/operator/encryption/helpers_test.go
- pkg/operator/encryption/key_controller.go
- pkg/operator/encryption/key_controller_test.go
- pkg/operator/encryption/migration_controller.go
- pkg/operator/encryption/migration_controller_test.go
- pkg/operator/encryption/prune_controller.go
- pkg/operator/encryption/prune_controller_test.go
- pkg/operator/encryption/state.go
- pkg/operator/encryption/state_controller.go
- pkg/operator/encryption/state_controller_test.go
- pkg/operator/encryption/state_test.go
This include a getDesiredEncryptionState cleanup with:
- move encryption config into the focus, secrets only give additional info about migration
- by that handle missing secrets (don't panic as before)
- fix bug that all existing keys are added as read keys
- in STEP 2, only add missing read-keys, never drop. We only drop in the last step after migration has finished. This makes us resilient to secret deletion. Conversely, when the config is deleted and we still have the secrets (and the resource list did not change, during upgrade it is a bad time to delete the config), we can reconstruct the config.
- added getDesiredEncryptionState unit tests
- make getDesiredEncryptionState handle nil configs correctly
- add state controller
> encryption: add prune controller

- pkg/operator/encryption/controllers.go
- pkg/operator/encryption/key_controller.go
- pkg/operator/encryption/key_controller_test.go
- pkg/operator/encryption/migration_controller.go
- pkg/operator/encryption/migration_controller_test.go
- pkg/operator/encryption/prune_controller.go
- pkg/operator/encryption/prune_controller_test.go
- pkg/operator/encryption/state.go
- pkg/operator/encryption/state_controller.go
- pkg/operator/encryption/state_controller_test.go
- key controller starts with the first key when the mode changes
- state controller follows key controller only
- when config or keys exists, resetting mode to "" has no effect,
other than being understood as identity, but leaves encryption
mechanism active.
> encryption: fix encryption bootstrap logic

- pkg/operator/encryption/key_controller.go
- pkg/operator/encryption/prune_controller.go
- pkg/operator/encryption/prune_controller_test.go
- pkg/operator/encryption/secrets.go
- pkg/operator/encryption/state.go
- pkg/operator/encryption/state_test.go
- pkg/operator/encryption/types.go
Secret names played a role for comparison which secrets are used in the config. This PR changes this by only taking the `<prefix>-<n>` number for sorting, but otherwise just compares mode and keys.
> encryption: decouple secret names from config

- bindata/v4.1.0/kube-apiserver/defaultconfig.yaml
- pkg/operator/v410_00_assets/bindata.go
Setting these higher. The kube-apiserver appears to be fine with more load.
> add max-in-flight

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
CRI-O 1.16 made a change to how selinux labels were handled that increased security. In doing so, it tightened security and needs to be explicitly told to not label a container. In the case of this initContainer, it is trying to edit the permissions of a file on the host system, which is (to SELinux) a security flaw, and thus selinux is denying it.
explicitly add privilege to the initContainer so it can touch the hostPath
Signed-off-by: Peter Hunt <pehunt@redhat.com>
> add privilege to operator init container

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
As it was previously assumed to be privileged (as it is static), as well as the other containers need write access to the audit logs
ref: https://storage.googleapis.com/origin-ci-test/logs/release-promote-openshift-machine-os-content-e2e-aws-4.3/2497/artifacts/e2e-aws/pods/openshift-kube-apiserver_kube-apiserver-ip-10-0-150-56.ec2.internal_kube-apiserver-4.log
from another failed promomtion job
Signed-off-by: Peter Hunt <pehunt@redhat.com>
> make whole kube-apiserver pod privileged

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
There is no pod-level security policy to set privileged. Instead, explicitly set privileged for every container in the pod that needs it (the two that mount audit-dir)
Signed-off-by: Peter Hunt <pehunt@redhat.com>
> Properly set pod as privileged

- .gitignore
- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
/cc @soltysh 
/hold
(just in case, I think this should fail on current offenders)
> Add alert for deprecated apis

- pkg/operator/configmetrics/configmetrics.go
We are going to soon start supporting instruction set architectures
other than x86_64/AMD64. This new metric will help use understand how
widely these different architectures are used.
The control plane will very likely always be homogeneous, so this metric
assumes that only a single architecture will be reported. Additionally,
for the foreseeable future, OpenShift will only support homogeneous
clusters, so reporting the architecture of the control plane will be
enough to know the architectures in use by the entire cluster.
> metrics: report the control plane architecture

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
/hold
We can't be sure the calert works and need to check manually because this alert is ignored - we can't unignore it at the same time because those are different repos.
/cc @soltysh
> Bug 1768417: Adjust UsingDeprecatedAPIExtensionsV1Beta1 alert

- manifests/0000_20_kube-apiserver-operator_02_service.yaml
- manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
- manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
- manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252
> Add manifest annotations for hosted deployment exclusions

- bindata/v4.1.0/kube-apiserver/kubeconfig-cm.yaml
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- pkg/operator/configobservation/apiserver/observe_apiserver.go
- pkg/operator/configobservation/apiserver/observe_apiserver_test.go
- pkg/operator/starter.go
- pkg/operator/v410_00_assets/bindata.go
Reverts openshift/cluster-kube-apiserver-operator#656
The PR was correct to wire it, but the locahost recovery seems to be wired wrong and neither CI nor the operator detect broken certsyncer :(
Installer pre-populates the files managed by certsyncer, so we never find out its broken in CI.
We need to revert until we have a fix for the localhost recovery SNI cert. And we need to wire certsyncer informers to fail after a while to get the container failing, or get healthz wired for that container in future.
```
E1120 08:48:02.984629       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ConfigMap: Unauthorized
E1120 08:48:02.988881       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Secret: Unauthorized
E1120 …
```
> Revert "Fix certsyncer to use longlived localhost-recovery cert for cert-syncer"

- Makefile
Operator e2e have side effects and need to run serially. Golang does that by default for unit tests in the same package but with addition of etcd tests in a different package, the e2e now collide and flake.
/cc @p0lyn0mial @sttts
> Fix e2e to run serially

- pkg/operator/configobservation/etcd/OWNERS
I was added here in 03b2b018d2 (#156), but I'm not sure what this package does, let alone how it should be maintained.
CC @abhinavdahiya in case he wants out too ;).
> pkg/operator/configobservation/etcd/OWNERS: Drop wking

- pkg/operator/configobservation/etcd/OWNERS
Bumping OWNERS per https://github.com/openshift/cluster-kube-apiserver-operator/pull/674
/cc @abhinavdahiya @alaypatel07
> pkg/operator/configobservation/etcd/OWNERS: add alaypatel07 and hexfusion

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/modules.txt
Pick of https://github.com/openshift/cluster-kube-apiserver-operator/pull/695.
> Bug 1775580: bump(library-go): handle deletion of target revision

- go.mod
- go.sum
- vendor/github.com/openshift/api/config/v1/types_feature.go
- vendor/github.com/openshift/api/go.mod
- vendor/modules.txt
Fetched the latest pseudoversion, used it in the replace directive.
Ran `go mod tidy` and `go mod vendor`.
Not sure I need to update something in https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/bindata/bootkube/config/bootstrap-config-overrides.yaml the same way it was done in https://github.com/openshift/cluster-kube-apiserver-operator/pull/658
> Consume the latest openshift api so sctp is enabled in lowlatency featureset

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/config/configdefaults/config_default.go
- vendor/modules.txt
* openshift/library-go#657 : config: default bind network to tcp instead of tcp4
> bump(*): openshift/library-go

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- pkg/cmd/render/render.go
- pkg/cmd/render/render_test.go
- pkg/operator/configobservation/network/observe_network.go
- pkg/operator/configobservation/network/observe_network_test.go
This updates our kube-apiserver config to specify a bind address of `::` rather than `0.0.0.0` when running in a single-stack IPv6 cluster. Combined with https://github.com/kubernetes/kubernetes/pull/84727 this will then cause it to advertise an IPv6 address for `kubernetes.default`.
Originally I modified both `bindata/bootkube/config/bootstrap-config-overrides.yaml` and `bindata/bootkube/config/config-overrides.yaml`, but the changes to the latter had no effect; I'm guessing that the "real" (post-bootstrap) config is rendered without access to the cluster manifets and so doesn't pass `--cluster-config-file`, so the whole `if len(renderConfig.ClusterCIDR) > 0` section just gets skipped. So instead I added the code to the config observer.
There is, at the moment, no simple way to test …
> If the cluster is single-stack IPv6, bind to :: rather than 0.0.0.0.

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Since `apps/v1beta1 and apps/v1beta2` are disabled in Kube `1.17` we can safely remove the mentioned alerts as any attempt to create a resource will immediately return an error.
I run the following commands on a quite recent cluster:
```
k get --raw /apis/apps/v1beta2
k get --raw /apis/apps/v1beta1
Error from server (NotFound): the server could not find the requested resource
```
Client/Server version:
```
k version                         
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0", GitCommit:"8a9ae19", GitTreeState:"clean", …
```
> removes unused UsingDeprecatedAPIAppsV1Beta1 and UsingDeprecatedAPIAppsV1Beta2 alerts

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps-gomod.mk
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
- vendor/modules.txt
* openshift/library-go@6c7d7cc3: staticpod: improve node not ready degraded message to include reason and message
* openshift/library-go@0b9c208d: build-machinery: Add human readable messages to go mod verify-deps
> bump(*): vendor update

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
These metrics have been deprecated in versions 1.14 and 1.15 of
kubernetes, so we can safely drop them.
Note that this was already introduced to [kube-prometheus](https://github.com/coreos/kube-prometheus), it would be good if you could find an automation way of syncing your ServiceMonitor manifests with that repo. That is the canonical place we in the monitoring team, with the help with outside contributions as well, improve metrics, alerting and recording rules.
We use jsonnet for this and import the repo and whenever we do jb update we sync with all the repos to bring in any new changes and improvements, see example PR -> https://github.com/openshift/cluster-monitoring-operator/pull/593/files But whatever works for you. :)
> manifests: Drop deprecated kubernetes metrics

- pkg/operator/certrotationcontroller/certrotationcontroller.go
It was printing `Shutting down CertRotation` right after start.
All callers wrap this in a `go` and unfortunatelly don't wait for it to end, as we don't support graceful termination yet, so I don't think we need a backport.
/cc @deads2k @mfojtik
> Fix certrotationcontroller.Run to wait for context to be canceled

- bindata/v4.1.0/kube-apiserver/pod.yaml
- cmd/cluster-kube-apiserver-operator/main.go
- go.mod
- go.sum
- pkg/cmd/certregenerationcontroller/cabundlesyncer.go
- pkg/cmd/certregenerationcontroller/cmd.go
- pkg/cmd/regeneratecerts/regenerate_certificates.go
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- pkg/operator/v410_00_assets/bindata.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/flags.go
- vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/monitoring_resource_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/core_getters.go
- vendor/modules.txt
Adds a container into kube-apiserver static pod that will automatically refresh certs if those are already expired.
https://github.com/openshift/enhancements/blob/master/enhancements/kube-apiserver/auto-cert-recovery.md
https://jira.coreos.com/browse/WRKLDS-100
TODO:
/cc @deads2k @sttts @soltysh @mfojtik
> Add cert regeneration controller

- bindata/v4.1.0/config/defaultconfig.yaml
- pkg/operator/v410_00_assets/bindata.go
more in line with real values.
/assign @smarterclayton
> bug 1797657: increase the max-requests limits

- pkg/operator/certrotationcontroller/certrotationcontroller.go
This will make DR easier to test and ensure rotation is working pretty well.
> bug 1797601: force cert rotation every couple days for development

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
We don't need revision suffix as the pod already has revision in label. The original intent was to make it clear which revision we have in artifact logs, but having this suffix makes it harder to debug or to get logs when debugging broken clusters.
Combined with https://github.com/kubernetes/kubernetes/pull/87809 I think we will get into desirable state :-)
/cc @deads2k 
/cc @smarterclayton
> Bug 1798048: bindata: remove revision suffix from containers

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- Add a PrometheusRule to aggregate the metric for in-flight requests into 4 time series per cluster - to monitor number of requests in flight for `kube-apiserver` and `openshift-apiserver` for `mutating` and `nonmutating` request type.
The new rule will provide us with insights on how loaded our api server(s) are globally.
> Bug 1798214: Add a PrometheusRule to aggregate in-flight requests

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
This is cosmetic change to kube-apiserver pod that preselect kube-apiserver container when calling `kubectl logs`. Users don't have to specify the container name anymore and api server container will be used by default.
It require `oc` from master, there is no change in behavior with older `oc`.
> bindata: preselect container name for oc

- go.mod
- go.sum
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/golang.mk
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/lib/version.mk
- vendor/github.com/openshift/library-go/alpha-build-machinery/make/targets/openshift/deps.mk
- vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
- vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/modules.txt
Update to fix the operator.  This cannot be done in the static pod code itself because some consumers like etcd still rely on those directly set conditions and removing them would break it.
> bug 1798725: static pod operator cannot be composed

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
This shouldn't have any effect on our alerts or dashboards as the buckets are cumulative and for those purposes the remaining buckets should be sufficient.
Note: this change was made in "upstream" kube-promethues repo, see background for this https://github.com/coreos/kube-prometheus/pull/387
> Bug 1801154: manifests/: Throw away unused high cardinality apiserver duration buckets

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
> Bug 1793850: Update UsingDeprecatedAPIExtensionsV1Beta1 alert

- bindata/v4.1.0/kube-apiserver/recovery-config.yaml
- bindata/v4.1.0/kube-apiserver/recovery-encryption-config.yaml
- pkg/operator/v410_00_assets/bindata.go
- pkg/recovery/apiserver.go
when starting a recovery API server we must also mount the encryption config otherwise we won't be able to decrypt certain resources for example `secrets and configmaps` and we won't be able to create new certificates.
> Bug 1785498: regenerate-certificates command blocked by error illegal base64 data at input byte 3

- test/e2e/bound_sa_token_test.go
Previously operator readiness was only checked at the start of the set of bound token controller tests. This introduced the possibility of the configmap deletion test triggering rollout of a new apiserver pod revision that the subsequent operand secret deletion test wouldn't wait for before starting.
> Bug 1802247: Check operator readiness before each bound token controller test

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
When using the baremetal infrastructure platform, the networking architecture
includes 3 Virtual IP addresses (VIPs).  For more information about the use
of these VIPs, see this document:
https://github.com/openshift/installer/blob/master/docs/design/baremetal/networking-infrastructure.md
By default, the kube-apiserver will advertise an IP address that it determines
from the default network interface.  When running in IPv4, we have been getting
lucky that the VIPs were never chosen.  They are always listed after the primary
address when you observe with "ip", and the same order is reflected in golang
when it iterates available IP addresses.
When we starting running IPv6 clusters, we observed kube-apiserver often
advertising one of the VIPs instead of the permanent IP address for the …
> baremetal: Explicitly advertise the host IP chosen by kubelet

- pkg/operator/configobservation/etcd/observe_etcd.go
- pkg/operator/configobservation/etcd/observe_etcd_test.go
To avoid errors in the bootstrap kube-apiserver, we want to avoid removing the bootstrap etcd member until after the bootstrapping is complete.  In addition, today we're using an etcd endpoint (etcd-bootstrap) which isn't valid most of the time.  This stops using that.
This could produce a short-term situation where the etcd health check fails until the in-cluster etcd is present. If this becomes a practical problem, we can add a check that pings all the etcds to see if at least one is up before proceeding, but I wouldnt' worry about it until it's actually a problem.
> bug 1805421: skip using bootstrap etcd

- go.mod
- go.sum
- pkg/cmd/certregenerationcontroller/cmd.go
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
- vendor/modules.txt
Delegated AuthN/AuthZ do not support setting tls SNI name, nor they are needed for certregenerationcontroller to run. The failure to read those is fatal and breaks the certregenerationcontroller before it even starts.
```
W0217 17:11:14.501686       1 cmd.go:195] Using insecure, self-signed certificates
I0217 17:11:14.502018       1 crypto.go:580] Generating new CA for cert-regeneration-controller-signer@1581959474 cert, and key in /tmp/serving-cert-276295724/serving-signer.crt, /tmp/serving-cert-276295724/serving-signer.key
I0217 17:11:15.746589       1 observer_polling.go:155] Starting file observer
W0217 17:11:15.761254       1 builder.go:174] unable to get owner reference (falling back to namespace): Get https://localhost:6443/api/v1/namespaces/openshift-kube-apiserver/pods: x509: …
```
> Bug 1805398: Disable delegated auth for recovery

- go.mod
- go.sum
- pkg/cmd/certregenerationcontroller/cmd.go
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
- vendor/modules.txt
backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/768
requires:
/cc @soltysh @deads2k
> [release-4.4] Bug 1771410: Disable delegated auth for recovery

- pkg/operator/certrotationcontroller/certrotationcontroller.go
This reverts commit 4f38d5351554f081dcf1628bba664708cc8ab9b2.
This makes 4.4 have a long rotation time again.
> Bug 1797593: Revert "force cert rotation every couple days for development"

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
This picks commit from https://github.com/openshift/cluster-kube-apiserver-operator/pull/730 and applies the same pattern to the remaining alerts.
/assign @tnozicka 
/cc @LiliC @cblecker
> Bug 1795617:  Remove entirely deprecated alerts

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
The kube-apiserver uses approximately 33% of master CPU in a
reasonable medium sized workload. Given a 1 core per master baseline
(since CPU is compressible and shared), assign the kube-apiserver
roughly 33% of that core on each master.
> Bug 1812583: Normalize CPU requests on masters

- pkg/cmd/certregenerationcontroller/cmd.go
Fixes
```
E0316 11:09:35.761846       1 configmap_cafile_content.go:246] key failed with : missing content for CA bundle "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
E0316 11:10:06.515529       1 configmap_cafile_content.go:246] kube-system/extension-apiserver-authentication failed with : missing content for CA bundle "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
```
/cc @sttts @deads2k @soltysh
> Bug 1813911: Disable serving for cert regeneration controller to avoid wrong dependency

- go.mod
- go.sum
- pkg/cmd/regeneratecerts/carry/kubecontrollermanager/certrotationcontroller/kubecontrollermanagercertrotation.go
- pkg/cmd/regeneratecerts/regenerate_certificates.go
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
- vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
- vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go
- vendor/github.com/openshift/library-go/pkg/controller/factory/factory.go
- vendor/github.com/openshift/library-go/pkg/controller/factory/interfaces.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
- vendor/github.com/openshift/library-go/pkg/operator/management/management_state_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
- vendor/modules.txt
* openshift/library-go@3a6456f: resourcemerge: Allow removing annotations/labels
* openshift/library-go@423e202: factory: allow for post-start hooks for custom triggers
* openshift/library-go@7c9065e: implements a generic workload controller
* openshift/library-go@522f72d: go mod tidy
* openshift/library-go@07fd01b: adds precondition function
* openshift/library-go@34fe6fc: factory: remove support for runtime object in queue
* openshift/library-go@07eabbf: nsfinalizer: migrate controller to factory
* openshift/library-go@488e1fa: apiservice: migrate controller to factory
* openshift/library-go@38b127e: certrotation: migrate controller to factory
* openshift/library-go@3f9a525: configobserver: migrate controller to factory
* openshift/library-go@5f7087d: management: migrate controller to …
> bump library-go

- pkg/cmd/certregenerationcontroller/cmd.go
backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/797
/cc @sttts @deads2k @soltysh
> [release-4.4] Bug 1813914: Disable serving for cert regeneration controller to avoid wrong dependency

- bindata/v4.1.0/config/config-overrides.yaml
- pkg/operator/v410_00_assets/bindata.go
- test/e2e/bound_sa_token_test.go
The default issuer for bound service account tokens is updated to point to the internal dns name of the kube apiserver to ensure compatibility with the `ServiceAccountIssuerDiscovery` feature [1] added in kube 1.18. This fix is intended to be backported to 4.4 (the release that added support for bound service account otkens) before GA to ensure that the default will be compatible from introduction with the discovery feature without having to update the issuer (which would involve reissuing all existing bound tokens).
1: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery
Related change: https://github.com/openshift/api/pull/617
> Bug 1819246: Set service account issuer to internal dns name of kube apiserver

- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
- vendor/modules.txt
We removed the controller that sets the condition `DefaultSecurityContextConstraintsUpgradeable` if any default SCC has been mutated. A cluster that already has user-modified default SCCs will have the above condition set. We need to remove the stale condition.
> Bug 1827337: Remove stale condition DefaultSecurityContextConstraintsUpgradeable

- pkg/operator/starter.go
We removed the controller that sets the condition `DefaultSecurityContextConstraintsUpgradeable` if any default SCC has been mutated. A cluster that already has user-modified default SCCs will have the above condition set. We need to remove the stale condition.
Some user may do force upgrade to OpenShift 4.4, so we need this fix to go in 4.4 to clean the stale condition.
> Bug 1827336: Remove stale condition

- manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
since https://github.com/openshift/cluster-version-operator/pull/318 merged we can have our relatedObjects created immediately so must-gather always works.
> Bug 1828830: add relatedobjects for immediate creation by CVO

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
- vendor/modules.txt
* openshift/library-go@f2030b8d: Fix ClusterOperator event when version changes
* openshift/library-go@65abf9cb: Bug 1832143: Prevent noisy events for ovirt cloud provider
> Bug 1832143: bump(*): vendor update

- bindata/v4.1.0/config/defaultconfig.yaml
- pkg/operator/v410_00_assets/bindata.go
If I understood https://github.com/golang/go/issues/39086 right, clients don't recover cleanly.  This *may* improve e2e test behavior if the requests were failing because we would not retry.
/assign @sttts
> bug 1837451: prevent goaway chance in kubeapiserver to avoid tripping up golang clients

- manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
- pkg/operator/starter.go
We need this information to understand certain bootstrapping loops caused by overly broad admission webhook configuration that prevent restarts.
> Bug 1838122: add admission webhooks to must-gather for kas-o

- pkg/cmd/resourcegraph/resourcegraph.go
Eventually we should probably find a way to auto-update these.  A someday project
> bug 1837881: remove humorous help from dev focused command

- pkg/operator/certrotationcontroller/certrotationcontroller.go
we need to do this and then revert it for 4.6.  Ideally, we only have this for 4.5
> Bug 1806980: remove override for fast cert rotation

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
There's already an InitContainer that does this, but it doesn't handle container restarts, only pod restarts.
> Bug 1837992: wait for port 6443 to be open in the kube-apiserver container; use ss isntead of lsof

- pkg/operator/certrotationcontroller/certrotationcontroller.go
Reverting https://github.com/openshift/cluster-kube-apiserver-operator/pull/863.
> Bug 1840597: Revert "remove override for fast cert rotation" for 4.6

- test/e2e/bound_sa_token_test.go
- test/library/library.go
this PR improves the SA tokens tests by identifying tests that roll out a new version and waiting until all APIs converge onto the same revision.
> make SA Token tests to wait for API Servers to be on the same revision

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
6080 is occupied by readyz container which does not free the port when the main container restarts (obviously).
Contrary, we probably don't have to wait for 6080 to free up because the readyz container terminate immediately on SIGTERM. Hence, the port has like 70s+ to become available which is more than enough, plus the init container already waits for the port.
> Bug 1843752: static pod: don't wait for 6080 in apiserver container

- pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
Fix flipping like:
```
- "service-account-issuer": []interface{}{string("https://ci-op-dgz95p2d-067ff-pxnzv-oidc.s3.amazonaws.com")},
+ "service-account-issuer": []string{"https://ci-op-dgz95p2d-067ff-pxnzv-oidc.s3.amazonaws.com"}
```
> auth-config-observation: fix unstructured issuer slice type

- go.mod
- go.sum
- pkg/operator/starter.go
- pkg/operator/terminationobserver/late_connections.go
- pkg/operator/terminationobserver/termination_observer.go
- vendor/github.com/openshift/library-go/pkg/operator/eventwatch/controller.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/modules.txt
This wire event watcher for `LateConnections` event that increase the `openshift_kube_apiserver_lateconnections_count` prometheus metric.
A follow up would be to add Prometheus Alert.
Blocked on https://github.com/openshift/origin/pull/25126
/hold
> Wire event watcher for LateConnections events

- test/e2e/clean_stale_condition_test.go
- test/library/operator_config.go
Add an e2e test to validates that stale condition DefaultSecurityContextConstraintsUpgradeable is removed from the status block.
> Bug 1829580: Add e2e test that ensures stale condition is removed

- bindata/v4.1.0/config/defaultconfig.yaml
- pkg/operator/v410_00_assets/bindata.go
This keeps the list of admission separate from the kube patches that we maintain for inspectability and reliability.
> pass admission plugins to be enabled

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
"ss" shows sockets in CLOSE-WAIT state, so it's more accurate.
There's already an InitContainer that waits, but it doesn't handle container
restarts, only pod restarts.
> Bug 1851066: 4.4: use "ss" instead of "lsof" to check port; check on container start

- pkg/cmd/checkendpoints/controller/connection_checker.go
- pkg/cmd/checkendpoints/controller/connection_checker_test.go
- pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Changed the names of the **PodNetworkConnectivityChecks** created by the **kube-apiserver-operator** to be of the form: 
_`${sourcePod}`_ `-to-` _`${descriptive-label}`_ `-` _`${targetEndpoint}`_.
Example descriptive labels:
* `storage-endpoint`
* `openshift-apiserver-service-endpoint`
* `openshift-apiserver-service`
The new names, when used in logs, events, etc., enable faster identification of what the purpose of the endpoint is  for a human reader when to compared to simply login an ip address and port.
> add target endpoint description to check name

- test/e2e/clean_stale_condition_test.go
- test/library/operator_config.go
Add an e2e test to validates that stale condition DefaultSecurityContextConstraintsUpgradeable is removed from the status block.
This is an e2e test for https://github.com/openshift/cluster-kube-apiserver-operator/pull/838 that we  validated manually to merge in time to make it for cut off.
> Bug 1829576: Add e2e test that ensures stale condition is removed

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/v4.1.0/config/config-overrides.yaml
- bindata/v4.1.0/config/defaultconfig.yaml
- pkg/operator/v410_00_assets/bindata.go
Switch all the "easy" settings to flags instead of config.  There is a little bit more that isn't too hard, but requires config observation changes.  Let's clear the early stuff first.  This makes us more kube-like and will help answer questions about "how do we do benchmark X" and it helps focus our patches.
/assign @sttts
> Set flags instead of different config format

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
kube-apiserver has a histogram `etcd_request_duration_seconds` that measures latency between the kube-apiserver and etcd instance. This metrics is currently dropped by cluster-prometheus. Enable this metrics in OpenShift so we have visibility into etcd latency.
We ensured that this does not enable other unwanted metrcis
> count by(__name__) ({__name__=~"etcd_request.+"})
etcd_request_duration_seconds_bucket
etcd_request_duration_seconds_count
etcd_request_duration_seconds_sum
TODO:
The monitoring team has suggested that we also do a followup PR to sync upstream (`kube-prometheus`) scrape definitions - https://github.com/coreos/kube-prometheus/blob/f4568b06dca6425b0ffda2e90486eb025328bf36/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet#L410
> enable etcd latency metrics in kube-apiserver

- bindata/v4.1.0/kube-apiserver/pod.yaml
- cmd/cluster-kube-apiserver-operator/main.go
- pkg/cmd/checkendpoints/cmd.go
- pkg/operator/v410_00_assets/bindata.go
Remove hard-coded namespace from check-endpoints command so that it can be used by other component.s
> point-to-point network check: add parameterized namespace

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/v410_00_assets/bindata.go
This 
- adds a /var/log/kube-apiserver/termination.log file to masters (sitting next to the audit logs we already have). It lists non-graceful terminations for easier CI and customer cluster analysis.
- lets the watch-termination binary create `NonGracefulTermination` events in the openshift-kube-apiserver namespace on next launch.
Container logs alone are not enough because logging during termination is broken, and we lose logs from old pods. So we have to persist the data somewhere on disk.
Etcd is also no option as etcd struggles with the same termination issues and is not reliable.
Depends on https://github.com/openshift/origin/pull/25192.
> Log non-graceful termination to /var/log/kube-apiserver/termination.log and stdout

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/cmd/checkendpoints/cmd.go
- pkg/cmd/checkendpoints/controller/connection_checker.go
- pkg/cmd/checkendpoints/controller/metrics.go
- pkg/operator/v410_00_assets/bindata.go
Add the following metrics to the check-endpoint utility:
* _`namespace`_`_endpoint_check_count`
* _`namespace`_`_endpoint_check_tcp_connect_latency_gauge`
* _`namespace`_`_endpoint_check_dns_resolve_latency_gauge`
Removed any dependencies on the kube-apisever pod.
> NOTE: metrics to be scraped by Prometheus in a followup PR
> add metric reporting to check-endpoints

- bindata/v4.1.0/kube-apiserver/kubeconfig-cm.yaml
- pkg/operator/v410_00_assets/bindata.go
The service account gets the service-account CA that is valid at the point of creation. So if the localhost-recovery CA is not yet part of the kube-apiserver serving CA (which is the case during bootstrapping), this service-account won't work with the localhost-recovery endpoints.
The serving CA bundle though is always correct as it changes with time.
Fixes https://github.com/openshift/cluster-kube-apiserver-operator/pull/663/commits/2a44f96452f248818ff4c2467d51eef50fd139f2#r456357777
Partly reverts https://github.com/openshift/cluster-kube-apiserver-operator/pull/663.
> kube-apiserver-cert-syncer-kubeconfig: point to serving cert

- pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
- pkg/operator/connectivitycheckcontroller/connectivity_checks.go
- pkg/operator/starter.go
Makes the creation, maintenance, and reaping of old connectivity checks re-useable and localizes the custom logic.
> make the connectivity check controller re-useable

- pkg/operator/certrotationcontroller/externalloadbalancer.go
The kube-apiserver operator is going to degraded state while changing ApiServer URL in Infrastructure config.
Note: If there is no port specified
Ref:
https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/pkg/operator/certrotationcontroller/externalloadbalancer.go#L24
I0511 16:20:50.553418 1 servicehostname.go:40] syncing servicenetwork hostnames: [172.30.0.1 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local openshift openshift.default openshift.default.svc openshift.default.svc.cluster.local]
I0511 16:20:50.553446 1 panic.go:679] Finished waiting for CertRotation
I0511 16:20:50.553456 1 panic.go:679] Shutting down CertRotation
panic: runtime error: slice bounds out of range [:-1]
goroutine 271 [running]: …
> Change the method to get the ApiServer hostname 

- go.mod
- go.sum
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/configobservation/network/observe_network.go
- pkg/operator/configobservation/network/observe_network_test.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
- vendor/github.com/openshift/library-go/pkg/operator/eventwatch/controller.go
- vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
- vendor/modules.txt
This PR adds support for configuring the servicesNodePortRange of the KubeAPIServerConfig via the network config API. This is necessary to handle cases where the default range (30000-32767) is not sufficient for users who have more services in their cluster than the range can handle.
> Support configuring ServicesNodePortRange via network config

- pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
- pkg/operator/connectivitycheckcontroller/connectivity_checks.go
Create node "scoped" connectivity checks who's source pod and endpoints can change over time. Requires https://github.com/openshift/cluster-kube-apiserver-operator/pull/914.
> connectivitycheckcontroller: name endpoints using node names

- pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
- pkg/operator/featureupgradablecontroller/feature_upgradeable_controller_test.go
LatencySensitive FeatureGate should allow upgrades according to
https://github.com/openshift/api/blob/7192180f496aab1f7659d8660fc360498bab498b/config/v1/types_feature.go#L38
> Bug 1861431: LatencySensitive feature gate allows upgrades

- pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
- pkg/operator/connectivitycheckcontroller/connectivity_checks.go
Event indicating endpoint updated should have a reason of `EndpointCheckUpdated`.
> connectivitycheckcontroller: fix incorrect event reason on update

- pkg/operator/featureupgradablecontroller/feature_upgradeable_controller.go
- pkg/operator/featureupgradablecontroller/feature_upgradeable_controller_test.go
LatencySensitive FeatureGate should allow upgrades according to
https://github.com/openshift/api/blob/7192180f496aab1f7659d8660fc360498bab498b/config/v1/types_feature.go#L38
This is a manual cherrypick from the release-4.5 branch
Signed-off-by: Francesco Romani <fromani@redhat.com>
> [release-4.4] Bug 1863076: LatencySensitive feature gate allows upgrades

- pkg/cmd/checkendpoints/controller/connection_checker.go
- pkg/cmd/checkendpoints/controller/connection_checker_test.go
- pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
- pkg/cmd/checkendpoints/controller/updates_manager.go
- pkg/cmd/checkendpoints/controller/updates_manager_test.go
When delaying the processing of updates for the purposes of sorting updates made out of order, sometimes delaying for the shorter check period is enough vs. the longer check timeout.
> check-endpoints: minimize sorting delay

- pkg/cmd/checkendpoints/controller/connection_checker.go
- pkg/cmd/checkendpoints/controller/connection_checker_test.go
- pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
- pkg/cmd/checkendpoints/controller/updates_manager.go
When a check results in a latency longer than the check period (1s), the result of a check is reported after the result of subsequent checks. This PR introduces a delay to give the long running checks a chance to be processed in the correct order.
Further enhancements in the followup PR: https://github.com/openshift/cluster-kube-apiserver-operator/pull/924
> check-endpoints: handle out of order results

- pkg/operator/connectivitycheckcontroller/connectivity_checks.go
We create a PodNetworkConnectivityCheck for each apiserver to etcd on a node, but we also have an etcd connection via localhost. This PR creates a PodNetworkConnectivityCheck for the localhost connection.
> connectivitycheckcontroller: create check for localhost etcd conn.

- pkg/operator/connectivitycheckcontroller/connectivity_checks.go
This makes contains checks easier.
> avoid overlaping connectivity check names

- test/e2e/token_inactivity_timeout_test.go
Currently all the inactivity timeout test failures are due to kube-apiserver not rolling out in anticipated time. One of the reasons for this delay could be a new revision being created while another one is in progress. This change aims to cut down this [flakiness](https://github.com/openshift/cluster-kube-apiserver-operator/pull/928).
> inactivity timeout test waits until all kube-apiservers are on same revision

- pkg/cmd/checkendpoints/cmd.go
- pkg/cmd/checkendpoints/controller/connection_checker.go
- pkg/cmd/checkendpoints/controller/metrics.go
- pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
Implement changes to the metric names and labels as discovered during reviews for better usability.
* Names changed to no longer be specific to the component check-endpoints is being run in. They will always be:
```
pod_network_connectivity_check_count
pod_network_connectivity_check_tcp_connect_latency_gauge
pod_network_connectivity_check_dns_resolve_latency_gauge
```
* `endpoint` labels renamed to `targetEndpoint` to avoid collisions with default label of the same name.
* `component` label added (e.g. openshift-kube-apiserver or openshift-apiserver) 
* `checkName` label added
> Bug 1874521: connectivity check metrics cannot be aggregated across components 

- pkg/cmd/checkendpoints/controller/backoff_recorder.go
- pkg/cmd/checkendpoints/controller/backoff_recorder_test.go
- pkg/cmd/checkendpoints/controller/connection_checker.go
- pkg/cmd/checkendpoints/controller/pod_network_connectivity_check_controller.go
If check-endpoints attempts to create:
* more than 30 events in 30 seconds or 
* 600 events in 10 minutes,
then suspend emitting connectivity events for the next 30 minutes to allow the cluster networking to stabilize.
> Bug 1877106: Connectivity checker creates excessive events and possibly etcd db growth on Azure

- pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Disable the ConnectivityCheckController.
> Bug 1876166: disable kube-apiserver connectivity checks 

- pkg/operator/certrotationcontroller/certrotationcontroller.go
This PR reverts the forced cert rotation changes made due to reduce
> Bug 1840116: revert the forced cert rotation changes

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Define dedicated flowschema and priority configuration that will protect openshift specific traffic.
- `SAR` and `tokenreviews` from both `oas` and `oauth` are very important
- kcm, other `oas` and `oauth` requests, `/metrics` requests from openshift-monitoring is pretty important
- openshift controller manager is as important as `kcm`.
- control plane operators are important (kas-o, oas-o, auth operator, etcd operator)
- `workloads-low` goes below the traffic defined above.
Question:
- do we want to include `cvo` in the control plane operators, or are there traffic from any other critical operators that we should protect?
New configuration:
After applying the above configuration, we can see that the number of requests from `workload-low` drops. This implies that traffic from oas, …
> protect openshift traffic by using dedicated flowschema

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Defined dedicated flowschema and priority configuration that will protect openshift specific traffic.
- `SAR` from `oas` is very important
- kcm, other `oas` requests, metrics requests from openshift-monitoring is pretty important
- control plane operators are important (kas-o, oas-o, auth operator, etcd operator)
- `workloads-low` goes below the traffic defined above.
Question:
- do we want to include `cvo` in the control plane operators, or are there traffic from any other critical operators that we should protect?
The new configuration:
After applying the above configuration, we can see that the number of requests from `workload-low` drops. This implies that traffic from oas, `/metrics` call from openshift monitoring, traffic from control plane operators are not being throttled …
> BUG 1885356: protect openshift traffic by using dedicated flowschema

- Dockerfile.rhel7
Updating ose-cluster-kube-apiserver-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-kube-apiserver-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-cluster-kube-apiserver-operator builder & base images to be consistent with ART

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Define dedicated flowschema and priority configuration that will protect openshift specific traffic.
- `SAR` from `oas` is very important (exempt)
- kcm, other `oas` requests, `oauth server` requests, metrics requests from openshift-monitoring is pretty important
- control plane operators are important (kas-o, oas-o, auth operator, etcd operator)
- `workloads-low` goes below the traffic defined above.
Question:
- is `tokenreviews` from `oas` as important as `SAR`?
- do we want to include `cvo` in the control plane operators, or are there traffic from any other critical operators that we should protect?
After applying the above configuration, we can see that the number of requests from `workload-low` drops. This implies that traffic from oas, `/metrics` call from openshift monitoring, …
> BUG 1885353: protect openshift traffic by using dedicated flowschema

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
Based on https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy we should always set `dnsPolicy: ClusterFirstWithHostNet` when we have `hostNetwork: true`. 
/assign @sttts
> Bug 1889308: Set dnsPolicy ClusterFirstWithHostNet to match hostNetwork

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
This is matches openshift/enhancements#414 and doesn't change existing behavior
---
Initial annotations were added a month ago via https://github.com/openshift/cluster-kube-apiserver-operator/pull/957. This file was added recently and probably the two PRs were interleaved.
> add current profile annotations to CVO manifests

- pkg/operator/connectivitycheckcontroller/connectivity_check_controller.go
Turning off again as it is preventing 4.6.0 -> 4.7 from completing successfully.
> connectivitycheckcontroller: disable by default

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- go.mod
- go.sum
- pkg/cmd/render/render_test.go
- pkg/operator/configobservation/network/observe_network.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/network/observe_network.go
- vendor/modules.txt
In a dual-stack cluster, kube-apiserver needs to know about both service CIDR ranges.
I considered just ignoring the bootstrap config, since we don't currently ever need dual-stack services to work at bootstrap time, but maybe we will in the future? (Note that for the runtime config we require the user to enable the feature gate explicitly via an install manifest, since it's still alpha, but it's difficult to figure out if they have done that from the bootstrap code so I just enabled it unconditionally in the bootstrap config if they specified dual-stack service CIDRs.)
/hold
depends on https://github.com/openshift/library-go/pull/925
> Bug 1888861: set servicesSubnet correctly in dual-stack clusters

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
While the current log directory permissions are restrictive and correct,
the file permissions are too permissive and it raises flags on
evaluations of the deployment. Let's instead change the permissions to
0600 which is more appropriate for these types of logs.
> Restrict log permissions

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- go.mod
- pkg/cmd/render/render_test.go
- pkg/operator/configobservation/network/observe_network.go
In a dual-stack cluster, kube-apiserver needs to know about both service CIDR ranges.
Backport of #986. Rather than also backporting the library-go portion this just imports the new 4.6 library-go function.
> Bug 1888862: [4.6] set servicesSubnet correctly in dual-stack clusters

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
This reverts commit 108e3673289e0a6d2c3493c4b711c203daba87cd (#987) which is causing that our static pods have in-cluster dns server injected (see https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/kubelet/network/dns/dns.go#L348-L352), which is problematic during upgrades. I'm talking with the node team how and if this is going to be solved in kubelet. 
/assign @sttts
> Revert "Set dnsPolicy ClusterFirstWithHostNet to match hostNetwork"

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
- pkg/cmd/render/render.go
- pkg/cmd/render/render_test.go
ref: https://issues.redhat.com/browse/CO-1266
render: read service-account-issuer from authentication config file
We need to support user-provided service-account-issuer for supporting user's pre existing IAM OIDC provider.
The user will provider the authentications.config.openshift.io/cluster object with the issuer at install-time
and the bootstrap-kube-apiserver should use that issuer to prevent in divergence from the real kube-apiserver.
So the render command accepts a flag pointing to a file for authentication object, which the render command reads
to extract the issuer from the spec and updates the bootstrap-apiserver-config.
render: accept user provided bound-service-account-signing keys for kube-apiserver
To support pre-existing IAM OIDC provider on AWS, we need an option to …
> Support user provided service-account-signing-key and issuer

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- pkg/cmd/render/render_test.go
The flag is required since kube 1.20
To be follower by a BZ to wire the proper key to the installer but we need to unblock the rebase.
/cc @sttts @marun
> Always set service-account-issuer flag

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
The `SAR` traffic is being allocated to `exempt` now, so `openshift-aggregated-api-delegated-auth` has been orphaned.
> remove priority config openshift-aggregated-api-delegated-auth

- pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
- pkg/operator/configobservation/auth/auth_serviceaccountissuer_test.go
Without the override, the KAS would point to its own IP which is not
covered by the default serving certificate.
/assign @marun 
/cc @tnozicka
> Bug 1906808: configobservation: override service-account-jwks-uri to use LB address

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- go.mod
- go.sum
- vendor/github.com/openshift/api/config/v1/types_feature.go
- vendor/modules.txt
bring https://github.com/openshift/api into apiserver.
> Bug 1914287: bring selflinks back for 4.7, they will be removed in 4.8

- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
- adjust graph titles 
- update the dashboard with changes in kube 1.20
- add new metrics to the dashboard
> Bug 1910140: fix the api dashboard with changes in upstream kube 1.20

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
The kube-apiserver is one of our most dynamic scaling components,
but the majority of clusters have a base load that is fairly
predictable of around 300 millicore. In order to get more headroom
for smaller clusters, adjust the out of the box request to a more
accurate default. All of the sidecars were measured in heavily
loaded production clusters as taking less than 5 millicore each,
and the core kube-apiserver is tweaked slightly.  CPU is burstable
so the apiserver will grow as necessary into slack capacity, while
still yielding to etcd on saturated masters.
/hold
Testing multiple changes together
> Bug 1920159: kube-apiservers overstate steady-state CPU needs slightly

- bindata/v4.1.0/kube-apiserver/delegated-incluster-authentication-rolebinding.yaml
- pkg/operator/starter.go
- pkg/operator/v410_00_assets/bindata.go
Add a rolebinding to gain access to the configmap which holds CA bundles for client authentication.  This should alllow delegated-authentication to terminate mTLS even if they cannot run subjectaccessreviews.
@sttts @stlaz @s-urbaniak Please inspect carefully to ensure the configmap is correct and matches the content expected.
> add rolebinding for delegated in-cluster authentication

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
Important Note: We support upgrade and downgrade - 4.7 to 4.6 downgrade would behave very badly (in a skew case). So we should NOT back port to 4.7
> switch to v1beta1 for the p&f APIs

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
livez didn't exist when we started.  Now it does.  Update.
We may want a startup probe distinct from livez now. 
/assign @sttts
> bug 1939227: make liveness hit livez

- pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
- pkg/operator/configobservation/auth/auth_serviceaccountissuer_test.go
I noticed that the API audiences were only being configured in the bootstrap phase to match the SA issuer, but during normal runtime, they would be rolled back to the default value.
Make the audiences always match the SA issuer.
/assign @marun
> config api-audiences along with SA issuer

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
This addresses a CI failure that caused kube-apiservers to ripple fail
`Liveness probe failed: HTTP probe failed with statuscode: 429`
> bug 1937916: add a flowschema to ensure that probes never get 429s

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
readyz has different semantics than healthz
/assign @sttts
> bug 1939226: make kube-apiserver readiness checks, check readyz

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
DeprecatedAPIInUse needs update after apiserver kube bump.
> Update DeprecatedAPIInUse alert for new release.

- Makefile
- bindata/v4.1.0/kube-apiserver/apiserver.openshift.io_deprecatedapirequests.yaml
- manifests/0000_20_kube-apiserver-operator_07_clusteroperator.yaml
- pkg/operator/starter.go
- pkg/operator/v410_00_assets/bindata.go
simple rebase of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1097 since normal work hours are over
> bug 1949306: add deprecated CRD manifest

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- test/e2e/deprecated_api_test.go
We don't care about the use of a deprecated API, unless it is being removed in the next release.
Rename the `DeprecatedAPIInUse` alert to `APIRemovedInNextReleaseInUse` to better reflect the intent of the alert.
> Bug 1949593: rename DeprecatedAPIInUse alert to APIRemovedInNextReleaseInUse

- go.mod
- go.sum
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/config/client/transport.go
- vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/unstructured.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/args.go
- vendor/modules.txt
* openshift/library-go@5df90a2a: provides CancelRequest method for the PreferredHost round tripper  to facilitate cancellation
* openshift/library-go@9c9b6ed0: Allow StaticResourceController to ignore NotFound
* openshift/library-go@e2421125: Add ServiceMonitor sync to CSI operators
* openshift/library-go@04e8cf0b: Add ServiceMonitor to ApplyDirectly
* openshift/library-go@5cf97eb2: Return errors from ApplyDirectly
* openshift/library-go@73c4ea10: static-pods: allow fast-forward to next revision with pending installer
* openshift/library-go@d6342ca9: static-pods: avoid noise from 'for <duration>' messages
* openshift/library-go@2b890d20: convenience functions for processing unstructured arguments
* openshift/library-go@8c6d5ea6: static-pods: always set installer reason string
* …
> Bug 1949418: bump(*): vendor update

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- pkg/test/assets_test.go
Alert message template when made to pass the `TestYamlCorrectness` test, results in an invalid message.
Fixed the template and exclude it from the test.
> Bug 1932165: variables in DeprecatedAPIInUse alert's annotations.message are not parsed to existing values

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
- bindata/bootkube/manifests/00_openshift-kube-apiserver-operator-ns.yaml
- bindata/v4.1.0/kube-apiserver/ns.yaml
- bindata/v4.1.0/kube-apiserver/pod.yaml
- bindata/v4.1.0/kube-apiserver/recovery-pod.yaml
- manifests/0000_20_kube-apiserver-operator_00_namespace.yaml
- manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
- pkg/operator/v410_00_assets/bindata.go
- pkg/recovery/apiserver_test.go
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
> Add management workload annotations

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
look back up to 4 hours to ensure we catch removed api usage during end-to-end tests.
> Bug 1949591: tweak removed api in use alert expression

- pkg/operator/starter.go
proof of openshift/library-go#1018
// minReadySeconds is the time to wait between the completion of an operand becoming ready (all containers ready)
// and starting the rollout onto the next node. This avoids a problem with an external load balancer that looks like
// 1. for some reason we have two instances, maybe a liveness check blipped on one node. it doesn't matter why
// 2. we bring down an instance on m0 to start a new revision
// 3. at this point we have one instance running on m1
// 4. m0 starts up and goes ready, but the LB ready check just timed out and is waiting for X seconds
// 5. we bring down an instance on m1 to start the new revision.
// 6. the LB thinks all backends are down and routes randomly
// 7. no profit.
// setting this field to 30s can prevent the kube-apiserver …
> Bug 1949956: add minreadyseconds to ensure we don't have an LB outage on kas

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/v4.1.0/kube-apiserver/pod.yaml
- bindata/v4.1.0/kube-apiserver/recovery-pod.yaml
- manifests/0000_20_kube-apiserver-operator_06_deployment.yaml
- pkg/operator/v410_00_assets/bindata.go
- pkg/recovery/apiserver_test.go
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
> Rename workload annotations

- go.mod
- go.sum
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
- vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
- vendor/modules.txt
/hold
This is just a proof PR for a library-go change.
> bug 1953798: stop doing live gets for optional cert syncer files that don't exist on disk yet

- go.mod
- go.sum
- vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
- vendor/modules.txt
proof of https://github.com/openshift/library-go/pull/1065
> bug 1955226: update library-go to avoid CRD update loop

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Previously, the bootstrap manifest defined a pod in the `kube-system` namespace. After bootstrap of an SNO cluster, the CKAO updated the same same file (/etc/kubernetes/manifests/kube-apiserver-pod.yaml) to define a pod in the `openshift-kube-apiserver` namespace. The kubelet did not appear to consistently tear down the containers of the old pod. If the previous apiserver or insecure readyz containers continued to run, the new pod failed to start due to 6443 and/or 6080 remaining bound by the old pod's containers.
/cc @sttts
> Bug 1956081: Update bootstrap manifest namespace for SNO compatibility

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
This pod needs a nominal request so that the workload partitioning
kubelet mutation can act upon it.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
> Add a nominal request to the kube-apiserver init container

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
We have seen evidence that kube-apiserver processes are not started after each other without overlap. This will make it visible.
> Bug 1958094: Add flock to kube-apiserver startup

- Makefile
- test/e2e-encryption-rotation/encryption_rotation_test.go
- test/e2e-encryption/encryption_test.go
The current timeout for all encryption tests is 4 hours.
Previously the time needed to roll out a new KAS was 15 minutes, due to a known issue on AWS with the NLB it can take now 22 minutes.
It means that the tests need ~25 min to make sure that all servers are on the same revision and it is safe to start the test.
Since the rotation scenario needs to enable the encryption first, then wait and check if all resources were migrated, then change the encryption key and check the migration again.
It means that only these tests will need ~1 hour just for installing the servers.
Thus this PR moves the rotation tests to a separate CI job.
It will shorten the overall time needed to test encryption but also increase the pass rate of the tests as we have seen them frequently failing to due to a …
> Bug 1943804: split encryption tests

- .ci-operator.yaml
We should be always using `rhel-8-release-golang-1.16-openshift-4.8` not `golang-1.16` since the other is deprecated and is missing a lot of tooling needed for build process. 
> Set proper root image in .ci-operator.yaml

- bindata/v4.1.0/alerts/cpu-utilization.yaml
- pkg/operator/v410_00_assets/bindata.go
1. brings in the lib-go fixes https://github.com/openshift/library-go/pull/1070
2. fixes the formatting for one naughty rule
3. writes up a dockerfile I used for testing.
> bug 1957645: avoid warm loop for writing prometheus rules

- Makefile
- bindata/v4.1.0/kube-apiserver/pod.yaml
- go.mod
- go.sum
- pkg/operator/configobservation/apiserver/observe_termination_duration.go
- pkg/operator/configobservation/apiserver/observe_termination_duration_test.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/starter.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
- pkg/operator/v410_00_assets/bindata.go
- pkg/test/assets_test.go
- test/e2e/user_certs_test.go
- vendor/github.com/openshift/library-go/test/library/encryption/e_log.go
- vendor/github.com/openshift/library-go/test/library/encryption/helpers.go
- vendor/modules.txt
Due to a known AWS issue: https://bugzilla.redhat.com/show_bug.cgi?id=1943804
the time needed for an LB to notice and remove unhealthy instances must be extended.
`shutdown-delay-duration` flag has been changed from `70s` to `210s` and `terminationGracePeriodSeconds` field from `135s` to` 275s`.
For `terminationGracePeriodSeconds` the initial `210s` is reserved for the minimal termination period.
Additional `60s` for finishing all in-flight requests and an extra `5s` to make sure a potential SIGTERM will be sent after a server terminates itself.
> Bug 1943804: increases termination timeouts for AWS

- bindata/v4.1.0/alerts/kube-apiserver-slos.yaml
- pkg/operator/starter.go
- pkg/operator/v410_00_assets/bindata.go
This PR copies the upstream [`KubeAPIErrorBudgetBurn` alerts](https://github.com/openshift/cluster-monitoring-operator/blob/6f22c3b33e2af7a61a3d385f0688d270519b49e4/assets/control-plane/prometheus-rule.yaml#L383-L436) and its recording
rules to CKAO. It updates the rules to:
1. Exclude long-running requests to subresources like`proxy`, `logs`, `exec` etc., 
from the error budget calculation. As described in 
https://bugzilla.redhat.com/show_bug.cgi?id=1953798#c1, these long-running 
`GET`, `LIST` requests are causing flakiness in the e2e parallel and upgrade 
jobs, due to slow resource reads.
1. Separate the request latency calculation by the request `scope` (i.e. `resource`,
`namespace`, `cluster`).
Subsequent PRs to fix other parts of the e2e test suites will follow, if the changes
in …
> Bug 1953798: Add apiserver burn rate SLO alerts

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
(Revert "Merge pull request #1060)
Use the flow schema introduced in upstream that exempts probes.
https://github.com/openshift/kubernetes/pull/656
> Bug 1956606: Revert "Merge pull request #1060" (Use the flow schema introduced in upstream)

- pkg/operator/configobservation/auth/webhook_authenticator.go
Set webhook authenticator's cache TTL to 30s to prevent very early
oauthaccesstoken timeouts.
---
as described in https://github.com/openshift/enhancements/pull/403
/assign @deads2k 
cc @s-urbaniak
> Bug 1967090: webhookauth observer: set cache TTL to 30s

- bindata/v4.1.0/alerts/api-usage.yaml
- pkg/operator/v410_00_assets/bindata.go
- pkg/test/assets_test.go
Counter-part to https://github.com/openshift/kubernetes/pull/784
> Bug 1966410: alert: exclude kcm samples from removed API alerts

- bindata/v4.1.0/alerts/kube-apiserver-slos.yaml
- pkg/operator/v410_00_assets/bindata.go
This PR fixes a typo in the `scope` label of the SLO recording rules.
> Bug 1953798: Fix incorrect 'scope' label in SLO recording rules

- pkg/operator/certrotationcontroller/certrotationcontroller.go
This switches back to normal 30 days rotation period (from 6h during development).
> Bug 1921139: remove override for fast cert rotation for release

- pkg/operator/certrotationcontroller/certrotationcontroller.go
Inverse of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1143 for master branch during development of 4.9.
> Bug 1921139: Revert "remove override for fast cert rotation for release"

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/preconditions.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/file_utils.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/copy.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
- vendor/modules.txt
As of today, the dynamic certificates i.e. `kube-apiserver-certs` are accessed by at least two processes, namely the installer pod and the cert-syncer.
Up until now, there was no coordination between these processes that might have lead to many unexpected errors, like https://bugzilla.redhat.com/show_bug.cgi?id=1963730
This PR writes all certificates in an atomic way by first creating a temporary file, writing the content to it, and then renaming it to the original file. 
`os.Rename` calls `syscall.Rename` which in turn uses the rename syscall (Linux) which provides atomicity (https://man7.org/linux/man-pages/man2/rename.2.html)
The previous attempt didn't work as it would break the DR scripts - https://github.com/openshift/library-go/pull/1098
>  kube-apiserver failed to load SNI cert and key

- go.mod
- pkg/cmd/insecurereadyz/readyz.go
- vendor/modules.txt
This PR reopens https://github.com/openshift/cluster-kube-apiserver-operator/pull/1130 to add graceful termination shutdown to the readyz endpoint. Originally we thought the bug had been fully fixed.
> Bug 1956081: add sigterm handler to insecurereadyz

- pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
api-audiences field was getting pruned which would result in a failing
cluster in case the service account issuer changed.
/assign @deads2k
> Bug 1974716: SA token issuer observer: fix observing api-audiences

- bindata/v4.1.0/config/defaultconfig.yaml
- pkg/operator/starter.go
- pkg/operator/v410_00_assets/bindata.go
The kubelet client cert - used by the apiserver to connect to the kubelet to execute commands such as such as `log` and `exec` - is already loaded dynamically. Update ckao to reflect this capability by writing the kubelet client cert secret to the unrevisioned cert path.
In addition to determining that dynamic reloading should be configured for non-empty cert and key file paths (as per the execution chain below), I manually verified cert reloading by adding debug logging to the dynamic cert loader that confirmed that the certs were loaded (at most once per second) on every invocation of log/exec/etc.
Execution chain guaranteeing dynamic loading of client cert + key:
- [Definition of kubelet client cert and key options](https://github.com/openshift/kubernetes/blob/master/cmd/kube-apiserver/ …
> Bug 1964231: Ensure kubelet client cert change does not require a restart

- pkg/operator/configobservation/apiserver/observe_termination_duration.go
- pkg/operator/configobservation/apiserver/observe_termination_duration_test.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
To get under 60s for termination+startup.
We might add a more graceful O(10s) timeout to non-long-running requests during termination as follow-up, if this solution turns out to be too bumpy.
> graceful-termination-duration: reduce to 15s for SNO

- bindata/v4.1.0/kube-apiserver/pod.yaml
- pkg/operator/v410_00_assets/bindata.go
to disable it even before we hit k8s 1.22
> disable apiextensions.k8s.io/v1beta1 and admissionregistration.k8s.io/v1beta1

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/condition_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/key_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/migration_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/prune_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers/state_controller.go
- vendor/modules.txt
It turns out that the new precondition checker added in 4.8 might prevent the encryption controllers from running and clearing the stale conditions.
This can happen especially on upgrades from 4.7 to 4.8.
https://github.com/openshift/library-go/pull/1125 changed the encryption controllers to clear stale conditions when the preconditions are not fulfilled. 
This PR incorporates it into this operator.
> clear encryption conditions when there is no work to be done

- bindata/assets/alerts/audit-errors.yaml
This takes into use the audit log metrics defined in the documentation
[1] and applies them to an alarm.
The purpose of the alarm is to inform administrators that there are
errors writing audit logs which might be an issue for incident response
teams as the audit logs become unreliable at this point. The alarm has a
query that provides appropriate labels to identify the API server
type and instance that's failing.
The alert is left vague enough that this will catch any API Server
causing these types of issues; but is still usable via the
aforementioned labels.
The alert will trigger if there are any errors detected (threshold above 0).
However, this happening is not a common occurrence, and would most
likely trigger for the following reasons:
* Node's disk space is full
* Someone actually …
> Create alert for API Server audit log errors

- go.mod
- go.sum
- pkg/operator/startupmonitorreadiness/readiness_checks.go
- pkg/operator/startupmonitorreadiness/readiness_checks_test.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock_linux.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock_others.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/annotations/annotations.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/assets/startup-monitor-pod.yaml
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/bindata.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/fallback.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/manage_pod.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/monitor.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/options.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/os.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/signal.go
- vendor/modules.txt
this PR implements the following checks
- checks if we are not dealing with the old kas
- checks kube-apiserver /healthz/etcd endpoint
- checks kube-apiserver /healthz endpoint
- checks kube-apiserver /readyz endpoint
- checks if the kas pod is running at the expected revision
- checks that kubelet has reporting readiness for the new pod
xref: openshift/enhancements#833
> introduces KubeAPIReadinessChecker used by startup monitor to assess Kube API server readiness/health condition

- bindata/assets/config/defaultconfig.yaml
Connections to kubelets have used HTTPS unconditionally since 1.19
Needed to land https://github.com/openshift/kubernetes/pull/862
/assign @sttts
> Drop kubelet-https removed in 1.22

- go.mod
- go.sum
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go
- vendor/modules.txt
Vendor in https://github.com/openshift/library-go/pull/1145.
> staticpod/installer: get rid of sleep in sync loop

- cmd/cluster-kube-apiserver-operator/main.go
- go.mod
- go.sum
- pkg/operator/starter.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/assets/startup-monitor-pod.yaml
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/fallback.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/options.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/pod_template.go
- vendor/modules.txt
requires https://github.com/openshift/library-go/pull/1130
xref: https://github.com/openshift/enhancements/pull/833
> Bug 1985997: wires the startup monitor

- Makefile
- test/e2e-sno-disruptive/sno_disruptive_test.go
I am going to define a dedicated CI job for the new tests.
> Bug 1985997: scaffolding for e2e tests for the static pod monitor

- bindata/assets/kube-apiserver/pod.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
This change the current logic of running kube-apiserver to following:
* **setup** init container (timeout={{.GracefulTerminationDuration + 35 + 5}})
* `flock -w {{.GracefulTerminationDuration}}` (normally 135s)
* on error: wait 60s for 8443 port to be released
* `flock -u`
* **kube-apiserver** container (_livenessProbe_ initial timeout=45s (time apiserver must respond to livez or die))
* `flock -w 30` (just to be safe)
* on error: exit(1)
* run watch-termination that run kube-apiserver
There are two cases we might hit:
* kubelet/CRI-O will launch a new kube-apiserver process while the previous one is still terminating: in that case, the setup container will wait up to 130s for the old kube-apiserver to release the lock. If it fails, it will wait for extra 60s for the 8443 port to be …
> Bug 1989461: kube-apiserver: make flock wait for release and remove port wait

- manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
The CMO is now capable of using client cert auth to scrape the metrics endpoints. Use that in our components to reduce API load and allow metrics collection when the API is down - given further authz conditions are met.
/cc @deads2k @s-urbaniak
> Bug 1986829: metrics: use client cert auth for metrics scraping 

- go.mod
- go.sum
- pkg/operator/startupmonitorreadiness/enablement.go
- test/e2e-sno-disruptive/helpers.go
- test/e2e-sno-disruptive/sno_disruptive_test.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/startupmonitorcondition/startup_monitor_condition.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
- vendor/modules.txt
Replacing https://github.com/openshift/cluster-kube-apiserver-operator/pull/1195. Enabling https://github.com/openshift/enhancements/blob/master/enhancements/kube-apiserver/startup-monitor.md for single node.
cc @romfreiman @eranco74
> Bug 1985997: Enable static pod fallback logic for SNO, with disruptive e2e test

- pkg/operator/startupmonitorreadiness/enablement.go
if no infra is found, its early in the cluster's lifespan, just return
false for whether to enable the startup monitor
Found in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-e2e-gcp-upgrade/1423126561342623744
> Bug 1990610: prevent panic in startup monitor enablement check

- bindata/assets/alerts/api-usage.yaml
- go.mod
- go.sum
- test/e2e/deprecated_api_test.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/modules.txt
Fix the bug on the installer_controller  to only be degraded if lastFailedRevision = TargetRevision
> Bug 1991357: bump library.go

- bindata/assets/alerts/kube-apiserver-slos.yaml
This fixes a bug in where the `kube-apiserver-operator` alerts do not have an appropriate namespace label. The lack of this label prevents them from being routed appropriately based on the fact they are a platform-impacting set of alerts.
> Bug 1985447: Add namespace labels to kube-apiserver-operator alerts

- pkg/operator/starter.go
This was added on https://github.com/openshift/cluster-kube-apiserver-operator/pull/1166
but that PR didn't actually create the rule. This fixes that.
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
> Bug 1994257: Actually create prometheus rule for audit error alert

- bindata/assets/alerts/api-usage.yaml
- bindata/assets/alerts/audit-errors.yaml
- bindata/assets/alerts/cpu-utilization.yaml
QE caught some additional alerts that didn't have the namespace set. This sets those namespaces.
> Bug 1985447: Add namespace label to remaining apiserver alerts

- pkg/operator/kubeletversionskewcontroller/kubelet_version_skew_controller.go
- pkg/operator/kubeletversionskewcontroller/kubelet_version_skew_controller_test.go
- pkg/operator/starter.go
Add `KubeletVersionSkewController` in support of enhancement user story: [APIServer - Enforce OpenShift's defined kubelet version skew policies](https://github.com/openshift/enhancements/blob/master/enhancements/update/eus-upgrades-mvp.md)
```go
// KubeletVersionSkewController sets Upgradeable=False if the kubelet
// version on a node prevents upgrading to a supported OCP version.
//
// For odd OCP minor versions, kubelet versions 0 or 1 minor version
// behind the API server version are supported.
//
// For even OCP minor versions, kubelet versions 0, 1, or 2 minor
// versions behind the API server version are supported.
const KubletVersionSkewLimitUpgradeable = "KubletVersionSkewLimitUpgradeable"
```
Reason | Upgradeable? | Description
-- | -- | --
KubeletVersionUnknown | Unknown | …
> Bug 1998552: Enforce OpenShift's defined kubelet version skew policies

- bindata/assets/config/defaultconfig.yaml
This is an attempt to enable the PodSecurity plugin to enable https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement
This can be merged once 4.10 master opens, the earliest.
/hold
> bindata: enable podsecurity plugin

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/modules.txt
Bumping to get https://github.com/openshift/library-go/pull/1180
> Bug 1993800: bump(library-go): staticpod/installer: fix backoff of installers

- bindata/assets/alerts/api-usage.yaml
- bindata/assets/alerts/cpu-utilization.yaml
- manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
1. Changed `message` annotations to `description` annotations.
2. Added `summary` annotations.
3. Ensure that the`description` annotation is _"...providing details about what is happening and how to resolve the issue"_.
> Bug 1992541: all the alert rules' annotations "summary" and "description" should comply with the OpenShift alerting guidelines

- bindata/assets/kube-apiserver/ns.yaml
- bindata/bootkube/manifests/00_openshift-kube-apiserver-ns.yaml
Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in openshift-kube-apiserver namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @deads2k @sttts
> podsecurity: enforce privileged for kube-apiserver

- bindata/assets/kube-apiserver/pod.yaml
config introduced to help 1.22 merging (https://github.com/openshift/cluster-kube-apiserver-operator/pull/1162) can be discarded now that 1.22 changes are in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#removal-of-several-beta-kubernetes-apis
> remove unncessary config

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
- vendor/modules.txt
```
2021-11-03T04:25:43.102203390Z F1103 04:25:43.102194       1 cmd.go:48] lstat /etc/kubernetes/static-pod-resources/kube-scheduler-certs: no such file or directory
2021-11-03T04:25:43.194947275Z goroutine 1 [running]:
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.stacks(0xc000012001, 0xc0001c81c0, 0x84, 0xda)
2021-11-03T04:25:43.194947275Z     k8s.io/klog/v2@v2.9.0/klog.go:1026 +0xb9
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.(*loggingT).output(0x3a8bd60, 0xc000000003, 0x0, 0x0, 0xc0003c81c0, 0x1, 0x2f628ac, 0x6, 0x30, 0x414600)
2021-11-03T04:25:43.194947275Z     k8s.io/klog/v2@v2.9.0/klog.go:975 +0x1e5
2021-11-03T04:25:43.194947275Z k8s.io/klog/v2.(*loggingT).printDepth(0x3a8bd60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000496910, 0x1, 0x1)
2021-11-03T04:25:43.194947275Z …
```
> bug 2026352: Sync with library-go to pick fixes for pruner panic

- test/e2e/user_certs_test.go
- test/library/crypto.go
Currently, server certs are signed using the server private key.
They should be signed by the CA's private key.
This fixes it.
/cc @openshift/openshift-team-auth-maintainers @soltysh @sttts
> test/e2e/TestNamedCertificates: sign using root CA

- go.mod
- go.sum
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/encryption/deployer/revisionedpod.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
- vendor/modules.txt
Backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1255 to release-4.9.
1.  If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
3. For branches that are in the Maintenance lifecycle phase:
4. The severity field of the bug must be set to accurately reflect criticality.
5. The PR was created with the cherry-pick bot OR the PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how …
> [release-4.9] Bug 2029504: encryption-controller: sync secrets conditionally

- bindata/assets/config/defaultconfig.yaml
This disable pod security admission for 4.10. We plan to activate it again in 4.11.
> Bug 2008462: config: disable pod security admission

- pkg/operator/webhooksupportabilitycontroller/conditions.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission_test.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_on_virtual_resource.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_on_virtual_resource_test.go
- pkg/operator/webhooksupportabilitycontroller/webhook_supportability_controller.go
Add new condition: `VirtualResourceAdmissionDegraded`
Add new reason: `AdmissionWebhookMatches`
> Bug 2033784: set kube-apiserver degraded=true if webhook matches a virtual resource

- go.mod
- go.sum
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
- vendor/modules.txt
Create a new guard controller which:
- create one guarding pod per each static operand (the guarding pod assume the operand has /readyz endpoint up and running)
- create a PDB with minAvailable when the topology is not SNO
- adjust PDB's minAvailable based on the number of master nodes available
- serves as a controller which recreates guarding pods there were deleted/terminated
> bug 2005901: Guard controller pdb

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
- bindata/assets/alerts/kube-apiserver-slos-extended.yaml
- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Update latency thresholds used to compute the kube-apiserver SLO to
align with results from sig-scalability.
https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md#definition
> Bug 2034559: alerts: update latency thresholds

- go.mod
- go.sum
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/metricscontroller/legacy_cn_certs_sync.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go
- vendor/modules.txt
To bring https://github.com/openshift/library-go/pull/1296
> bug 2044622: staticpod pruner: check if the cert directory exists to avoid panic

- pkg/operator/starter.go
- pkg/operator/webhooksupportabilitycontroller/webhook_supportability_controller.go
Give customers running mis-configured webhooks before 4.10 a chance to upgrade to 4.10 before they are forced to fix their webhooks.
> Bug 2052513: disable webhook supportability during upgrade

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodfallback/static_pod_fallback_condition.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/modules.txt
picking up openshift/library-go#1302
pick of [#736 ](https://github.com/openshift/cluster-kube-apiserver-operator/pull/1300) into 4.10
> bug 2053148: [release-4.10] update library-go to get rapid installer pod fixes

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
- vendor/github.com/openshift/library-go/pkg/operator/management/management_state.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
- vendor/modules.txt
This is the library-go bump for backport 4.8 on bug 2026089 which changes cert permissions.
> [release-4.8] Bug 2026089: library-go bump

- pkg/operator/starter.go
Since counters are monotonic, their values are not reset, hence we have to use the `increase` function to detect faulty certificates. Here, a window of 30 minutes has been chosen to have a good reaction time after certs have been corrected.
/cc @tkashem @p0lyn0mial
> Bug 2037274: pkg/operator#LegacyCNCerts: use increase function

- bindata/assets/alerts/api-usage.yaml
- test/e2e/deprecated_api_test.go
* `APIRemovedInNextEUSReleaseInUse` should alert on use of APIs removed in OpenShift 4.11 & 4.12 (kube api server versions 1.24 and 1.25).
* `APIRemovedInNextReleaseInUse` should alert on use of APIs removed in OpenShift v4.11 (kube api server version 1.24).
* Added `TestAPIRemovedInNextEUSReleaseInUse` e2e test.
Once OpenShift 4.11 has been rebased onto kube apiserver 1.24, this will need to be updated again.
> Bug 2067384: OCP 4.10 should be firing APIRemovedInNextEUSReleaseInUse for APIs removed in 1.25

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
The label has been renamed from `requestKind` to `request_kind` for the `apiserver_current_inflight_requests` metric.
https://github.com/kubernetes/kubernetes/pull/91177 in 1.19
The recording rule needs to be updated.
> fix label for max-in-flight-recorder

- Dockerfile.rhel7
these appear consistently in the bootstrap kube-apiserver log and are not valuable.
> E0404 19:03:15.520793       1 apiaccess_count_controller.go:161] the server could not find the requested resource (post apirequestcounts.apiserver.openshift.io)
E0404 19:03:16.933062       1 apiaccess_count_controller.go:161] the server could not find the requested resource (post apirequestcounts.apiserver.openshift.io)
E0404 19:03:17.578002       1 apiaccess_count_controller.go:161] the server could not find the requested resource (post apirequestcounts.apiserver.openshift.io)
E0404 19:03:20.997276       1 apiaccess_count_controller.go:161] the server could not find the requested resource (post apirequestcounts.apiserver.openshift.io)
E0404 19:03:23.063800       1 apiaccess_count_controller.go:161] the …
> render apirequest count to reduce startup errors

- bindata/assets/config/defaultconfig.yaml
This enables the PodSecurity admission with baseline level (for now). I suspect it might break tests, which is where @s-urbaniak's upstream involvement in the e2e framework might come handy.
/cc @s-urbaniak 
/cc @openshift/openshift-team-auth-maintainers
> AUTH-2: reenable PodSecurity on privileged level

- bindata/assets/config/defaultconfig.yaml
starting with 1.24 `enable-swagger-ui` server option has been removed. See https://github.com/kubernetes/kubernetes/commit/206f3aeec2748ef149a36a9c69329b5be2953ecb
The rebase PR is seeing this error from bootstrap:
```
E0425 13:41:01.547406       1 run.go:74] "command failed" err="unknown flag: --enable-swagger-ui"
```
> [v1.24] remove enable-swagger-ui from default config

- bindata/assets/kube-apiserver/pod.yaml
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
From the upstream release notes:
> Kubernetes 1.24 bumped version of golang it is compiled with to go1.18, which introduced significant changes to its garbage collection algorithm. As a result, we observed an increase in memory usage for kube-apiserver in larger an heavily loaded clusters up to ~25% (with the benefit of API call latencies drop by up to 10x on 99th percentiles). If the memory increase is not acceptable for you you can mitigate by setting GOGC env variable (for our tests using GOGC=63 brings memory usage back to original value, although the exact value may depend on usage patterns on your cluster).
Since kube-apiserver is managed by an operator on OpenShift, they'll need a configuration knob to tune this value if desired.
> Bug 2074031: Support tuning GOGC within a limited range.

- bindata/assets/alerts/podsecurity-violations.yaml
- pkg/operator/starter.go
- pkg/test/assets_test.go
Cluster administrators should be aware when a Pod Security violation
occurs as that might cause workloads to break in the next .y OpenShift
version.
/cc @ibihim @s-urbaniak
> Bug 2100155: Add new alert on Pod Security violations

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/bindata/bindata.go
- vendor/modules.txt
1.  If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
3. For branches that are in the Maintenance lifecycle phase:
4. The severity field of the bug must be set to accurately reflect criticality.
5. The PR was created with the cherry-pick bot OR the PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
> [release-4.10] Bug 2060058: superfluous apirequestcount entries in audit log

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/images.go
- vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
- vendor/modules.txt
This PR bumps the library-go dependency to include the change[1] that
enables external cloud provider for OpenStack by default.
[1] https://github.com/openshift/library-go/pull/1383
> Update library-go to enable external provider for OpenStack by default

- bindata/assets/config/defaultconfig.yaml
Also removes the warn and audit levels as these are driven
by the enforcement policy.
/assign @ibihim 
/assign @deads2k
> make PodSecurity admission enforce restricted globally

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
- vendor/github.com/openshift/library-go/pkg/config/serving/server.go
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/modules.txt
[Trt-589](https://issues.redhat.com//browse/Trt-589) is researching an issue where installer pods timeout, shutdown and enter a failed state triggering KubePodNotReady alerts.  library-go was updated to add milestone logging to track the progress and track down the issue.  Bumping the version to pull those changes in.
> trt-589 bump library-go

- bindata/assets/alerts/api-usage.yaml
- test/e2e/certrotation_test.go
> Update API alerts after recent bump to k8s 1.25

- bindata/assets/alerts/api-usage.yaml
There may be version skew around updates, where an alert gets bumped to consider 1.26 "the next release" while other cluster components are still running 1.25, or vice versa.  This change makes it a bit easier to understand those skew issues by explicitly including in the alert `description` (and Telemetry-uploaded alert labels) the `removed_release` value we're complaining about.
> bindata/assets/alerts/api-usage: Include removed_release in APIRemovedInNext*ReleaseInUse labels

- pkg/operator/configobservation/auth/auth_serviceaccountissuer.go
- pkg/operator/configobservation/auth/auth_serviceaccountissuer_test.go
- pkg/operator/serviceaccountissuercontroller/serviceaccountissuer_controller.go
- pkg/operator/serviceaccountissuercontroller/serviceaccountissuer_controller_test.go
- test/e2e/serviceaccountissuer_test.go
As documented in https://github.com/openshift/cluster-kube-apiserver-operator/blob/005a95607cf9f8db490e962b549811d8bc0c5eaf/bindata/assets/config/config-overrides.yaml#L8 we set the default value for service account issuer if one is not specified in authentication config. This was missed in the original controller design, and we have to account for this default value. When the user specifies a custom issuer in auth config, we must preserve the default value previously used and keep it as a trusted value.
> serviceaccountissuer: fix case when default value is being used and not trusted after change

- bindata/assets/alerts/kube-apiserver-slos.yaml
- pkg/operator/starter.go
- use conditional static resource functionality
- delete prometheusrules/kube-apiserver-slos
> Bug 2094362: Duplicate prometheus rules for API SLOs after upgrade

- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-anyuid.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostaccess.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork-v2.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostnetwork.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot-v2.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-nonroot.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted-v2.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-restricted.yaml
"`ephemeral`" volumes, called as [Generic Ephemeral Volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes) in upstream docs, are volumes represented by a [PersistentVolumeClaim template in a Pod](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes).
`ephemeral` is already part of upstream `restricted` policy: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
Using these volumes is safe for any user, as users with the capability to use "`ephemeral`" volumes can only fool Kubernetes to create PVCs, in the same fashion as users that can create StatefulSets can fool Kubernetes to create PVCs.
In both cases, the created PVC is subject of namespace's PVC quota. From Kubernetes/OCP …
> Bug 2100429: Allow ephemeral volumes in all SCCs

- bindata/assets/config/defaultconfig.yaml
This reverts commit fe247321ae0f9130ab54b2cf16f6a0b4b5250b54.
> OCPBUGS-3663: Revert "turn PodSecurity admission to enforce restricted globally"

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/modules.txt
To avoid:
```
Oct 28 23:58:55.693391 ci-op-3hj6pnwf-4f6ab-lv57z-master-1 kubenswrapper[1657]: E1028 23:58:55.693346    1657 kubelet_pods.go:413] "Hostname for pod was too long, truncated it" podName="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-master-1" hostnameMaxLen=63 truncatedHostname="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-maste"
Oct 28 23:59:03.735726 ci-op-3hj6pnwf-4f6ab-lv57z-master-0 kubenswrapper[1670]: E1028 23:59:03.735671    1670 kubelet_pods.go:413] "Hostname for pod was too long, truncated it" podName="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-master-0" hostnameMaxLen=63 truncatedHostname="openshift-kube-scheduler-guard-ci-op-3hj6pnwf-4f6ab-lv57z-maste"
Oct 28 23:59:11.168082 ci-op-3hj6pnwf-4f6ab-lv57z-master-2 …
```
> OCPBUGS-3041: guard controller: set an explicit hostname to avoid name collisions

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
These flags were removed in https://github.com/kubernetes/kubernetes/pull/112120, based on [the defaults](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md#logging-defaults)  we should be good with just dropping these flags.
> Drop flags removed in k8s 1.26

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
This reverts commit 6d1def163cf897b6ca54da16bdc1f444bbae5607.
This results in log files getting wiped on restart, I'm also investigating some CI failures and would like to rule
this out as a cause.
> Revert "drop log-file flag removed in 1.26"

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
- bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
- bindata/bootkube/manifests/secret-bound-sa-token-signing-key.yaml
- bindata/bootkube/manifests/secret-control-plane-client-signer.yaml
- bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
- bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
- bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
- bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
- go.mod
- go.sum
- pkg/test/assets_test.go
- vendor/github.com/openshift/library-go/pkg/assets/assets.go
- vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/render/render.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/modules.txt
Backporting https://github.com/openshift/cluster-kube-apiserver-operator/pull/1410
> OCPBUGS-4478: guard controller: set an explicit hostname to avoid name collisions

- bindata/bootkube/bootstrap-manifests/kube-apiserver-pod.yaml
Previously deprecated klog flags will be removed completely in kube 1.26.
Logs of bootstrap pods were previously using the --log-file flag, will be available in the cri-o container logs instead.
> remove use of deprecated klog flags

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- pkg/cmd/render/render.go
This is a precursor to a future update that will enable the new discovery API once we update to 1.26.  We want the *only* form of discovery ever available to be aggregated so that we can flush out problems in our new install clusters instead of having clients coast on caches.
/assign @tkashem
/cc @soltysh
> make the bootstrap kube-apiserver honor cluster-wide featuregates

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
- bindata/assets/alerts/kube-apiserver-slos-extended.yaml
Update the SLO alerts to include some improvements from upstream and revert some changes that were made downstream which broke the alerts.
Improvements:
- use new `apiserver_request_slo_duration_seconds` metric which excludes webhook latency and errors 
- exclude `attach` and `portforward` subresources from latency calculation since they are long-running requests
- revert changes from https://github.com/openshift/cluster-kube-apiserver-operator/commit/622c08f101555be4584cb897f68f772777b32ada since this is not a typo, it is meant to catch metrics for which requests don't have a scope and add them to the resource-scoped SLO. Not sure if this is still relevant but I'd rather not diverge from upstream for something so minor that doesn't have any impact
- revert expression related changes from …
> API-1520: Update SLO alerts based on upstream improvements

- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
The etcd_object_counts metric is deprecated and was replaced by the stable apiserver_storage_objects metric.
> OCPBUGS-5873: dashboard: use apiserver_storage_objects metric

- bindata/bootkube/config/bootstrap-config-overrides.yaml
- pkg/cmd/render/render.go
this is a backport of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1419
/cc @deads2k @ibihim
> [4.12] OCPBUGS-6789: make the bootstrap kube-apiserver honor cluster-wide featuregates

- test/e2e/bound_sa_token_test.go
We need to disable this test for now because it puts the CI cluster in an unstable state.
https://issues.redhat.com/browse/OCPBUGS-8529 is a blocker bug against OpenShift 4.13 that tracks the effort of fixing this behavior.
> OCPBUGS-8478: Disable TestBoundTokenSignerController

- manifests/0000_20_kube-apiserver-operator_08_flowschema.yaml
- `assuredConcurrencyShares` has been rename to `nominalConcurrencyShares`
- two new field `lendablePercent` and `borrowingLimitPercent` have been added for borrowing
https://github.com/kubernetes/kubernetes/blob/172431ebf15b9d85406202365c697a7b925e0efe/staging/src/k8s.io/api/flowcontrol/v1beta3/types.go#L476-L503
we have a dedicated PriorityLevel for our control plane operators, and we are saying that 33% of its capacity can be borrowed by other priority levels if need be.
> OCPBUGS-10577: update apf configuration to use v1beta3

- go.mod
- go.sum
- pkg/operator/configobservation/auth/podsecurityadmission_test.go
- vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go
- vendor/modules.txt
Minor follow-up for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1485#pullrequestreview-1400370715.
> Cover featuregate access errors in PSA configobserver unit tests.

- bindata/assets/alerts/api-usage.yaml
Alert needs to bump removed_release versions after 1.27 rebase
> OCPBUGS-14038: Update APIRemovedInNextRelease alerts

- pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion.go
- pkg/operator/webhooksupportabilitycontroller/webhook_supportability_controller.go
This PR puts the name of the webook into the log file which makes debugging easier.
In addition to that I have realised that the controller reacts to changes made to any CRD which increases the frequency of running checks. I changed the controller to react only to changes made to CRDs that have webhook configuration defined.
On my local cluster (4.14) I have noticed frequent changes to `egressqoses.k8s.ovn.org` and `egressfirewalls.k8s.ovn.org` CRDs
```
oc get crds egressqoses.k8s.ovn.org -w
oc get crds egressfirewalls.k8s.ovn.org -w
```
Perhaps only changes to the `managedField` but still worth further investigation.
@oarribas would you be interested in taking a closer look at ^ ?
TODO: (separate PRs)
[X] I found out that the `Controller %q resync interval is set to %s which might lead …
> OCPBUGS-13946: degraded_webhook.go x509: certificate signed by unknown authority

- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
It looks like the previous metric used in the dashboard (`apiserver_longrunning_gauge`) metric was depreciated in `1.23` (upstream) - https://github.com/kubernetes/kubernetes/issues/103441
The new metric is `apiserver_longrunning_requests`(used in this PR)  - https://github.com/kubernetes/kubernetes/pull/103799/files
The old metric was removed in https://github.com/kubernetes/kubernetes/commit/731397086b763b9a951a414d37018f7e4f03b99c
and at the same time the new metrics was promoted to "STABLE" level.
> OCPBUGS-14940: api_performance_dashboard: show apiserver_longrunning_requests metric

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
Add more recording rules to reduce the load on Thanos querier and Prometheus. Adding more recording rules allows Prometheus to store metrics aggregation up front and request less information every time a dashboard is reloaded.
This removes "auto" interval as it can't be cached via recording rules.
Verified by deploying this as an additional dashboard and comparing the result - graphs are almost identical.
> OCPBUGS-3986: dashboard: use recording rules for most metrics

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
the prevoius `apiserver_dropped_requests` metric was depreciated in https://github.com/kubernetes/kubernetes/pull/110337
xref: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1518
> api_performance_dashboard: show apiserver_request_total instead of apiserver_dropped_requests

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
the `prevoius apiserver_registered_watchers` metric was depreciated in https://github.com/kubernetes/kubernetes/pull/110337
grouping by `group` and `resource` gives us:
grouping by `group` only gives us:
an empty `group` indicates the `core` group, not sure if it could be shown somehow.
> api_performance_dashboard: show apiserver_longrunning_requests metric

- pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission.go
Previously the dial timeout to a webook was set to one second which seems to be very aggressive and could cause failures which could put the operator into degraded state.
This PR reads the timeout value for a webhook from the spec or uses a default value of 10 seconds if it wasn't specified
> OCPBUGS-13946: do not use one second timeout when asserting a webhook connection

- pkg/operator/certrotationcontroller/certrotationcontroller.go
we haven’t been paged because the `recovery-controller` will create a new certificate (when the old expires) and because the cert is actually auto-reloaded.
> certrotation: rotate kube-apiserver-to-kubelet-signer when 80% of validity is over

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
In https://github.com/openshift/cluster-kube-apiserver-operator/pull/1484 recording rules were added to the PrometheusRule which was supposed to be removed by CVO (it has `release.openshift.io/delete: "true"` annotation). This PR moves recording rules to a new PrometheusRule - and fixes missing datapoints on apiservers dashboard.
After https://github.com/openshift/cluster-authentication-operator/pull/616 was merged openshift-oauth-apiserver is available on the dashboard, so this PR updates recording rules to include it as well.
This also removes unnecessary v2 suffix in dashboard name
> OCPBUGS-15489: manifests: add new PrometheusRule for recording rules

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/allrequestbodies-rules.yaml
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/manifests/writerequestbodies-rules.yaml
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/allrequestbodies.yaml
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/multipleCr.yaml
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/oauth.yaml
- vendor/github.com/openshift/library-go/pkg/operator/apiserver/audit/testdata/writerequestbodies.yaml
- vendor/modules.txt
- Bump library-go
- Contains updated audit policies to not log tokens.
> OCPBUGS-13346: dont log jwt tokens

- bindata/assets/config/defaultconfig.yaml
- bindata/bootkube/config/bootstrap-config-overrides.yaml
- pkg/cmd/render/render.go
- pkg/cmd/render/render_test.go
- pkg/operator/configobservation/apienablement/observe_runtime_config.go
- pkg/operator/configobservation/apienablement/observe_runtime_config_test.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
This supports feature sets containing gates that depend on disabled-by-default API group-versions.
> Set runtime-config in lockstep with feature-gates, if needed.

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
The kube-apiserver PrometheusRule was marked to be deleted by CVO in 4.13, so it is now safe to remove the manifest in 4.14.
> OCPBUGS-15504: manifest: remove kube-apiserver PrometheusRule

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
In order to avoid additional load on Prometheus the recording rules for kube-apiserver dashboard are not included when Console capability is not enablked . These are not used anywhere else, so it should not affect any other components.
> OCPBUGS-18247: manifests: don't include recording rules when Console capability is not enabled

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/modules.txt
This PR bumps library-go to get the latest static pod permissions(more specifically https://github.com/openshift/library-go/pull/1576).
> [release-4.14] OCPBUGS-19553: Update static pod manifests perms

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/modules.txt
This PR bumps library-go to fetch the changes come with;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546
> [release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks

- pkg/operator/configobservation/apienablement/observe_runtime_config.go
In 1.29, ValidatingAdmissionPolicy requires admissionregistration.k8s.io/v1beta1, not admissionregistration.k8s.io/v1alpha1.
> Update required GV for ValidatingAdmissionPolicy gate.

- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
In [previous PR](https://github.com/openshift/cluster-kube-apiserver-operator/pull/1542) this manifests was labelled as "available only when Console capability enabled". This causes CVO to force enable Console capability when upgrading from baseline 4.13 cluster - as this manifest is present.
In order to avoid this, the manifest needs to be renamed, so that CVO would treat it as a new one (since its applicability has changed)
> OCPBUGS-20331: manifests: rename API performance dashboard

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
Exactly like 7457da4fc0 (#1565), this pivot:
* Turns the original (group, namepspace, name) into a delete manifest, with no capability annotation (all clusters should delete this resource).
* Creates a (group, namespace, newName) manifest with the original spec content and capability annotation (only clusters with the cap enabled should have this resource).
which allows updates like:
1. Old release with the old (kind, group, namepspace, name) not annotated for a capability.
2. Request update to new release.
3. Outgoing cluster-version operator compares the outgoing manifests with the incoming manifests to decide if any capabilities need to be implicitly enabled:
1. It sees that the old (kind, group, namepspace, name) isn't labeled with any capabilities, so no need to implicitly enable …
> OCPBUGS-20331: manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver: Rename to kube-apiserver-performance-recording-rules

- go.mod
- go.sum
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/OWNERS
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
- vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/manifests/guard-pod.yaml
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/startupmonitor/cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
- vendor/modules.txt
allow eviction of unhealthy (not ready) pods even if there are no disruptions
allowed on a PodDisruptionBudget. This can help to drain/maintain a node and
recover without a manual intervention when multiple instances of nodes or pods
are misbehaving. Use this with caution, as this option can disrupt perspective
pods that have not yet had a chance to become healthy.
> OCPBUGS-23796: use AlwaysAllow UnhealthyPodEvictionPolicy option

- go.mod
- go.sum
- pkg/operator/podsecurityreadinesscontroller/conditions.go
- pkg/operator/podsecurityreadinesscontroller/conditions_test.go
- pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller.go
- pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller_test.go
- pkg/operator/podsecurityreadinesscontroller/warning.go
- pkg/operator/podsecurityreadinesscontroller/warning_test.go
- pkg/operator/starter.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
- vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
- vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
- vendor/k8s.io/pod-security-admission/LICENSE
- vendor/k8s.io/pod-security-admission/api/attributes.go
- vendor/k8s.io/pod-security-admission/api/constants.go
- vendor/k8s.io/pod-security-admission/api/doc.go
- vendor/k8s.io/pod-security-admission/api/helpers.go
- vendor/modules.txt
Backport of: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1588
Cherry-pick not working as it contains a bumped library-go for release 4.14.
Add Cluster Fleet Evaluation for Pod Security admission to release 4.14
We want to evaluate how many namespaces are violating across clusters that send telemetry.
> [4.14] OCPBUGS-25384: psa cluster fleet evaluation

- pkg/operator/webhooksupportabilitycontroller/conditions.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission_test.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion_test.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_on_virtual_resource.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_on_virtual_resource_test.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_test.go
This is clearly a gap in the platform. Perhaps the best way would be to introduce a readiness condition `kas` would honour. On the other hand the issue is not that severe since most of the time it will appear during a webhook installation. I've checked and the cert-manager works exactly in the same way.
Initially I was thinking about waiting for a caBundle to be populated but realised it would hide the issue. I've changed the PR to report the issue instead.
> OCPBUGS-24005: webhookcontroller: report when a webhook resource is missing a caBundle provided by the service-ca-operator

- manifests/0000_90_kube-apiserver-operator_03_servicemonitor.yaml
The TechPreviewNoUpgrade alert used to have an expression that was only excluding the default feature set meaning that all other feature set were reported as causing the cluster to be unupgradeable. However, that is not the case for the LatencySensitive feature set. As such, this change limit the list of feature set causing this alert to fire to:
- TechPreviewNoUpgrade
- CustomNoUpgrade
Also, since the original name of this alert wasn't generic enough compare to its scope, it was renamed to UnsupportedFeatureSetEnabled.
> OCPBUGS-14496: manifests: fix the scope of the TechPreviewNoUpgrade alert

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go
- vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go
- vendor/modules.txt
This reduces the 
> Operation cannot be fulfilled on kubeapiservers.operator.openshift.io
messages in the log.  I found 50-100 in runs prior to the update here.
After this update had 5.
> NO-ISSUE: prevent update status conflicts 

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
- bindata/assets/alerts/kube-apiserver-slos-extended.yaml
- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
The apiserver_request_sli_duration_seconds metric was introduced as a
replacement of apiserver_request_slo_duration_seconds which is
deprecated in Kubernetes 1.27. This is just a renaming so besides
finding and replacing the name of the metrics no other action is
necessary.
To also avoid storing duplicated data in Prometheus, we need to drop
the apiserver_request_slo_duration_seconds at the ServiceMonitor level.
> OCPBUGS-18939: manifest: drop slo latency metrics in favor of sli

- bindata/bootkube/manifests/configmap-admin-kubeconfig-client-ca.yaml
This comes from the installer, but it's not user provided. It is logically owned by the kube-apiserver and something must manage the equivalent when the admin.kubeconfig expires.  We're close to that point.
> NO-JIRA: Add ownership for the admin kubeconfig

- pkg/operator/webhooksupportabilitycontroller/degraded_webhook.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_admission_test.go
- pkg/operator/webhooksupportabilitycontroller/degraded_webhook_conversion_test.go
for easier troubleshooting when a check is skipped because `service-ca` hasn't provided a CA for the webook we should also log the name of the webhook.
> OCPBUGS-24005: when skipping a webhook check because of missing CA log the name of the webhook

- pkg/operator/configmetrics/configmetrics.go
This will help track installations for third party platform (such as OCI) integrating through external platform
> OBSDA-553: add provider name to cluster_infrastructure_provider when external platform

- pkg/operator/certrotationcontroller/certrotationcontroller.go
This is necessary to test multi year time skew, so that CSRs could be approved using localhost-recovery kubeconfig
> NO-JIRA: extend node-system-admin-client validity to 2 years

- go.mod
- go.sum
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
- vendor/github.com/openshift/library-go/pkg/operator/configobserver/cloudprovider/observe_cloudprovider.go
- vendor/github.com/openshift/library-go/pkg/operator/render/options/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/config.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go
- vendor/modules.txt
As of 4.15, all feature gates for external cloud providers were promoted to GA. We therefore no longer need to have conditional logic to determine if the CCMs should be out of tree or not.
This has been updated in library-go but also needs to be updated here before we can remove the feature gates.
> OCPCLOUD-2514: External CCM should no longer rely on feature gate access

- pkg/operator/certrotationcontroller/certrotationcontroller.go
This annotation ensures that the component certificates will be automatically regenerated when the cluster is offline (suspended or shutdown).
https://github.com/openshift/release/pull/49238 will ensure these tests are being run
> NO-JIRA: certrotationcontroller: set AutoRegenerateAfterOfflineExpiry

- pkg/operator/certrotationcontroller/certrotationcontroller.go
This reverts commit 6f3faa4beae08550e95f0fc124f49b9e6baca52c introduced in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1652
We have multiple controllers reconciling the same resource at the same time without any coordination.
For example the `kube-control-plane-signer-ca` configmap is synced by 4 controllers (actually it is 8 because we have 2 processes).
Since the mentioned PR added a distinct annotation (`AutoRegenerateAfterOfflineExpiry`) for the same configmap it caused a hot update loop since the configmap was different.
The conflict error can be seen [even on a successful run ](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1577/pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-aws-ov …
> NO-ISSUE: Revert "certrotationcontroller: set AutoRegenerateAfterOfflineExpiry for generated certificates

- go.mod
- go.sum
- pkg/operator/certrotationcontroller/certrotationcontroller.go
- test/e2e/certrotation_test.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
- vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
- vendor/modules.txt
UseSecretUpdateOnly is intended as a short term hack for a very specific use case,
and it works in tandem with a particular carry patch applied to the openshift kube-apiserver.
(https://github.com/openshift/kubernetes/pull/1924)
we will remove this when we migrate all of the affected secret
objects to their intended type: https://issues.redhat.com/browse/API-1800
in short tls secrets used by this operator are reconciled
by multiple controllers ([the cert controller run by the operator](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/pkg/operator/certrotationcontroller/certrotationcontroller.go#L85) and [the same controller run by the recovery pod](https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/pkg/cmd/recoverycontroller/c …
> OCPBUGS-31807: Use RotatedSigningCASecret in update only mode

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
This includes cherrypicks of:
* https://github.com/openshift/cluster-kube-apiserver-operator/pull/1484
* https://github.com/openshift/cluster-kube-apiserver-operator/pull/1521
* https://github.com/openshift/cluster-kube-apiserver-operator/pull/1542
* https://github.com/openshift/cluster-kube-apiserver-operator/pull/1565
on release-4.13
> OCPBUGS-25922: [release-4.13] dashboard: use recording rules for most metrics

- bindata/assets/alerts/cpu-utilization-sno.yaml
- pkg/operator/starter.go
- pkg/operator/workloadpartitioning/cpuPartitioningAlertRenderer.go
- vendor/k8s.io/utils/cpuset/OWNERS
- vendor/k8s.io/utils/cpuset/cpuset.go
- vendor/modules.txt
Create separate SNO alert for control plane high cpu usage. This alert is also aware of workload partitioning and adjusts threshold if workload partitioning is enabled.
I don't track performance profile because after applying new one, node restarts and I can recreate/update alert threshold with new cores amount
> OCPEDGE-902: add SNO control plane high cpu usage alert

- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-hostmount.yaml
The SCC is named "hostmount-anyuid", and not just "hostmount", so I'm not sure this cluster role ever worked correctly.
> OCPBUGS-33184: Fix incorrect name for hostmount-anyuid SCC ClusterRole

- bindata/assets/kube-apiserver/storage-version-migration-flowschema-v1beta3.yaml
- bindata/assets/kube-apiserver/storage-version-migration-prioritylevelconfiguration-v1beta3.yaml
- pkg/operator/starter.go
The v1alpha1 version of the flowcontrol.apiserver.k8s.io group is removed in 4.16. Clusters installed prior to 4.8 may still have flowcontrol resources that were persisted using v1alpha1. If the storage version of those resources is not migrated before updating to 4.16, they will not be decodable. This ultimately prevents kube-apiserver instances from becoming ready.
> OCPBUGS-33963: Create one-shot migrations for the flowcontrol group.

- bindata/assets/alerts/api-usage.yaml
APIRemovedInNextReleaseInUse: 1.30 -> 1.31
APIRemovedInNextEUSReleaseInUse: 1.3[01] -> 1.31
> OCPBUGS-34800: Update APIRemovedInNextReleaseInUse for kube 1.30 / ocp 4.17

- bindata/assets/config/defaultconfig.yaml
PersistentVolumeLabel admission plugin needs a valid cloud config. kube-apiserver does not get it in OCP 4.17, and thus it rejects valid in-tree GCE PersistentVolumes.
The admission plugin was deprecated upstream a long time ago, it was removed from Kubernetes 1.31 (OCP 4.18) and it cannot work without a cloud provider in kube-apiserver anyway.
cc @openshift/storage
> OCPBUGS-34544: Disable PersistentVolumeLabel admission plugin

- bindata/bootkube/manifests/configmap-kubelet-bootstrap-kubeconfig-ca.yaml
Make sure kubelet-bootstrap-kubeconfig (generated by installer) is annotated
> OCPBUGS-34782: manifests: add ownership annotation for kubelet-bootstrap-kubeconfig

- bindata/assets/alerts/cpu-utilization.yaml
As discussed at https://github.com/openshift/cluster-kube-apiserver-operator/pull/1676#discussion_r1601703298, reverting SNO section on alert description and making deployment available only at non SNO clusters
> OCPEDGE-1102: Revert high cpu usage alert description

- pkg/operator/podsecurityreadinesscontroller/conditions.go
- pkg/operator/podsecurityreadinesscontroller/conditions_test.go
- pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller.go
- pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller_test.go
- pkg/operator/podsecurityreadinesscontroller/violation.go
- Add a new reason that is being set if a customer disabled the label syncer.
- Check only namespaces, where we at least own one label.
We want to:
- identify who disabled it and will have a failing workload and
- "properly" calculate PSA violations and not "believe" every label we find
> AUTH-521: add disabled syncer as reason to CFE for PSA

- pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller.go
- pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller_test.go
Kubeconfigs are parsed as TLS artifact registry sources, so secrets containing kubeconfigs should have necessary annotations
> NO-JIRA: nodekubeconfigcontroller: set ownership component for node kubeconfigs

- pkg/operator/certrotationcontroller/certrotationcontroller.go
Reverts openshift/cluster-kube-apiserver-operator#1661
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1721 has landed, so the controllers should no longer hotloop
> NO-JIRA: Re-apply "certrotationcontroller: set AutoRegenerateAfterOfflineExpiry for generated certificates"

- pkg/operator/starter.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Prevent apiserver from pointing to a single etcd endpoint (IP and localhost), which will lose connection when the single etcd is being updated
> OCPBUGS-42083: Don't rollout revision until three etcd endpoints are listed

- Dockerfile.rhel7
Updating ose-cluster-kube-apiserver-operator-container image to be consistent with ART for 4.17. There is a go version error fo origin PR https://github.com/openshift/cluster-kube-apiserver-operator/pull/1691 was created by [openshift-bot](https://github.com/openshift-bot), have to create new one manually and closing the PR https://github.com/openshift/cluster-kube-apiserver-operator/pull/1691.
> OCPBUGS-34310: Updating ose-cluster-kube-apiserver-operator-container image to be consistent with ART for 4.17

- bindata/assets/alerts/api-usage.yaml
The e2e test for the alert is currently failing because Kubernetes was updated to 1.32, but the alert wasn't updated: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1792/pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-gcp-operator/1884920095281516544.
> NO-JIRA: alerts: update APIRemovedInNextEUSReleaseInUse for 1.32

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
- bindata/assets/alerts/kube-apiserver-slos-extended.yaml
The problem that I recently noticed with the existing expression is that when we compute the overall burnrate from write and read requests, we take the ratio of successful read requests and we sum it to the one of write requests. But both of these ratios are calculated against their relevant request type, not the total number of requests. This is only correct when the proportion of write and read requests is equal.
For example, let's imagine a scenario where 40% of requests are write requests and their success during a disruption is only 50%. Whilst for read requests we have 90% of success.
apiserver_request:burnrate1h{verb="write"} would be equal to `2/4` and apiserver_request:burnrate1h{verb="read"} would be `1/6`.
The sum of these as these by the alert today would be equal to …
> OCPBUGS-49764: bindata/alerts/slo: improve burnrate calculation

- test/e2e-sno-disruptive/sno_disruptive_test.go
PR fixed: 
1. It takes longer to wait for the condition ‵StaticPodFallbackRevisionDegraded` to be true , about 15mins,
The case execution time takes about 20mins, 
```
$ go test -v -timeout 25m ./test/e2e-sno-disruptive; oc get co/kube-apiserver
=== RUN   TestFallback
...
Jan 24 15:20:50.867: Starting the fallback test
Jan 24 15:20:51.653: Setting UnsupportedConfigOverrides to map[]
Jan 24 15:20:52.808: Waiting 2m0s for the cluster to be in a good condition, interval = 20s, timeout 10m0s
Jan 24 15:22:53.409: The cluster has been in good condition for 2m0s
Jan 24 15:22:53.716: Setting UnsupportedConfigOverrides to map[apiServerArguments:map[non-existing-flag:[true]]]
Jan 24 15:22:55.866: Waiting for StaticPodFallbackRevisionDegraded condition, interval = 20s, timeout = 18m0s
Jan 24 …
```
> OCPQE-28167: Increase waitForFallbackDegradedConditionTimeout

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
- bindata/assets/alerts/kube-apiserver-slos-extended.yaml
While investigating https://issues.redhat.com//browse/OCPBUGS-42083, we noticed that some of the disruption was caused by 500 errors on health endpoints that were due to timeout, but the timeout for these endpoints is lower than it is for the other kube-apiserver endpoints.
Since we can already monitor these endpoints from the probes, I'd be better to remove them from the SLO alert to reduce its scope.
> OCPBUGS-49763: Disregard health endpoints in the burn rate alerts

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
see https://issues.redhat.com/browse/OCPBUGS-49980, there are 2 `sum:apiserver_request:burnrate5m` recording rule for 4.19, change the rate[6h] one to correct recording name `sum:apiserver_request:burnrate6h`
> OCPBUGS-49980: change one sum:apiserver_request:burnrate5m to sum:apiserver_request:burnrate6h

- bindata/assets/kube-apiserver/trusted-ca-cm.yaml
- bindata/bootkube/manifests/configmap-admin-kubeconfig-client-ca.yaml
- bindata/bootkube/manifests/configmap-csr-controller-ca.yaml
- bindata/bootkube/manifests/secret-aggregator-client-signer.yaml
- bindata/bootkube/manifests/secret-control-plane-client-signer.yaml
- bindata/bootkube/manifests/secret-kube-apiserver-to-kubelet-signer.yaml
- bindata/bootkube/manifests/secret-loadbalancer-serving-signer.yaml
- bindata/bootkube/manifests/secret-localhost-serving-signer.yaml
- bindata/bootkube/manifests/secret-service-network-serving-signer.yaml
- pkg/operator/certrotationcontroller/certrotationcontroller.go
This adds description to certificates managed by cluster-kube-apiserver-operator. These are taken from https://github.com/openshift/api/tree/master/tls/docs
> API-1689: TLS registry: add description

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Compare the etcd-servers list of URLs to the list of endpoints exposed
by cluster-etcd-operator to make sure that the kube-apiserver config has
at least two endpoints that are not localhost and bootstrap to satisfy
HA requirements.
> OCPBUGS-48673: targetconfigcontroller: check live etcd endpoints

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- The kube-scheduler-operator has already set the TraceAll to 10, as seen in https://github.com/openshift/cluster-kube-scheduler-operator/blame/b1cc4471e2f6c5dc81b2b9471f4634f1ecdb88b4/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L267
- The kube-controller-manager-operator also set the TraceAll to 10 **https://github.com/openshift/cluster-kube-controller-manager-operator/blob/9a7a572080a663bda581c0567e3921a99acd993e/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L540**
If we use TraceALL, we want to trace all the logs really, and some important k8s logs are v(10)
> NO-ISSUE: Bump TraceAll log level to v=10

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
- bindata/assets/alerts/kube-apiserver-slos-extended.yaml
this also fixes a bad `le="30(.0)?"` as a result of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1742
The chosen approach is to move to float buckets one Prometheus v3 is merged forgetting about the integer historical data.
That will be done in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1816
> MON-4129: revert https://github.com/openshift/cluster-kube-apiserver-operator/pull/1784

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
- bindata/assets/alerts/kube-apiserver-slos-extended.yaml
ensure all series involved in the different queries change
during the integer->float transition so that rate calculation remains consistent across all series.
If apiserver_request_sli_duration_seconds_bucket{le="1"} had a last value of 15 and
then apiserver_request_sli_duration_seconds_bucket{le=~"1.0"} reappeared with 20, the
rate calculated over a range where both {le="1"} and {le="1.0"} overlap will not
account for the 20−15=5 difference, as the two series are distinct. But
apiserver_request_sli_duration_seconds_count's rate will still take
that 5 jump into account as the series doesn't change.
Replace apiserver_request_sli_duration_seconds_count with
apiserver_request_sli_duration_seconds_bucket{le=~"60(.0)?"}
since they should be equal given that the timeout is 60s and cannot be …
> MON-4129: slos: accomodate for Prometheus v3 "le" normalization

- pkg/operator/configobservation/auth/auth_metadata.go
- pkg/operator/configobservation/auth/auth_metadata_test.go
- pkg/operator/configobservation/auth/external_oidc.go
- pkg/operator/configobservation/auth/external_oidc_test.go
- pkg/operator/configobservation/auth/webhook_authenticator.go
- pkg/operator/configobservation/auth/webhook_authenticator_test.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/starter.go
This PR does the following:
- adds unit tests for the `AuthMetadata` config observer
- adds a new config observer for direct OIDC; the config observer:
- detects auth type `OIDC` and the structured auth config CM in `openshift-config-managed` (created by the CAO in [cluster-authentication-operator#713](https://github.com/openshift/cluster-authentication-operator/pull/713))
- copies it to `openshift-kube-apiserver` where it will be used as a revisioned configmap and synced to a static file on all KAS nodes
- enables OIDC config via the `--authentication-config` CLI flag of the KAS pods
- modifies the `AuthMetadata` and `WebhookTokenAuthenticator` config observers to delete their respective resources when auth type `OIDC` is detected
Enhancement: …
> AUTH-541: OIDC structured auth config

- bindata/assets/alerts/kube-apiserver-slos-basic.yaml
- bindata/assets/alerts/kube-apiserver-slos-extended.yaml
Cherry-pick of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1744 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1804 to 4.18.
> [release-4.18] OCPBUGS-49898: bindata/alerts/slo: improve burnrate calculation

- pkg/operator/certrotationcontroller/certrotationcontroller.go
Some certificates should be excepted from rotation being set sizty times faster in development mode - i.e. localhost-recovery.kubeconfig
> OCPBUGS-55274: Change validity / refresh for some certs which should not be affected by dev cycle rotation change

- pkg/operator/certrotationcontroller/certrotationcontroller.go
Reverts openshift/cluster-kube-apiserver-operator#1830 and reapplies https://github.com/openshift/release/pull/58130
> OCPBUGS-43777: certrotationcontroller: run tests which runs deployment and creates projects - reapply

- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_cr-scc-hostmount-anyuid-v2.yaml
- bindata/bootkube/scc-manifests/0000_20_kube-apiserver-operator_00_scc-hostmount-anyuid-v2.yaml
the intent of hostmount-anyuid is to allow a pod access to paths on the host. The problem is, hostPath volumes aren't selinux relabeled, and there are paths that the default selinux type `container_t` cannot access.
This breaks expectation, and makes pods that rely on hostmount-anyuid brittle to selinux changes on the host (see https://issues.redhat.com/browse/OCPBUGS-55013)
Instead of relaxing permissions of all paths on the host, or increasing the ability of container_t, we should trust pods that are granted access to this already powerful SCC to use its power fully.
> OCPBUGS-55013: SCC: add hostmount-anyuid-v2

- pkg/operator/podsecurityreadinesscontroller/conditions.go
- pkg/operator/podsecurityreadinesscontroller/conditions_test.go
- pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller.go
- pkg/operator/podsecurityreadinesscontroller/podsecurityreadinesscontroller_test.go
- pkg/operator/podsecurityreadinesscontroller/violation.go
- pkg/operator/podsecurityreadinesscontroller/violation_test.go
Don't attempt to pick the stricter of the warn or audit PSS labels to determine whether the namespace is violating - look directly at the new MinimallySufficientPodSecurityStandard label instead.
> NO-JIRA: Use new PSS annotation

- pkg/operator/configobservation/apienablement/observe_runtime_config.go
I'm [trying to enable MutatingAdmissionPolicy](https://github.com/openshift/api/pull/2349) in tech preview clusters.
This should enable the API group so that MAPs can be served.
> NO-JIRA: Enable MutatingAdmissionPolicy group version

- manifests/0000_90_kube-apiserver-operator_04_servicemonitor-apiserver.yaml
- manifests/0000_90_kube-apiserver-operator_05_api_performance_dashboard.yaml
These yamls only works when upgrade from 4.14, no need in the newest 4.20 versions
next steps of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1565
> NO-JIRA: remove unused yaml

- bindata/assets/config/defaultconfig.yaml
- pkg/operator/configobservation/apiserver/observe_admission_plugins.go
- pkg/operator/configobservation/apiserver/observe_admission_plugins_test.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
When auth type is not OAuth (i.e. `OIDC` or `None`), we must disable the plugins relevant for RoleBindingRestrictions, as this API relies on the User & Group APIs, which are part of the OAuth apiserver.
This PR does the following:
- adds a generic config observer for admission plugins, which manages the `apiServerArguments.enable-admission-plugins` and `apiServerArguments.disable-admission-plugins` fields of the KAS config
- adds two special merge rules for the fields mentioned above
- removes RoleBindingRestriction related plugins from `defaultconfig.yaml`; these are now managed by the admission plugins config observer
**_Why a generic admission plugin config observer and not specific to the RBR plugins?_**
There are mainly two reasons behind this choice:
1. Follow the config observer …
> CNTRLPLANE-79: Disable oauth admission plugins

- pkg/operator/configobservation/apienablement/observe_runtime_config.go
ValidatingAdmissionPolicy currently depends on admissionregistration.k8s.io/v1 and the feature gate is always on. The v1beta1 version wasn't meant to be served outside of tech preview clusters.
Resumes the work started in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1687.
> OCPBUGS-55465: Stop serving admissionregistration.k8s.io/v1beta1.

- pkg/cmd/certregenerationcontroller/cmd.go
First configInformers was started to fetch featureGates, now it needs to be started again for certrotation controllers to be able to start informers
> OCPBUGS-56551: certregenerationcontroller: start configInformers again

- bindata/assets/config/defaultconfig.yaml
This should mostly eliminate aligned informer re-lists during kube-apiserver rollout.
> NO-JIRA: Enable watch termination grace period

- bindata/assets/config/defaultconfig.yaml
Reverts openshift/cluster-kube-apiserver-operator#1846
See https://issues.redhat.com/browse/OCPBUGS-58158 for details
To re-test before bringing back in, I'd try /payload 4.20 ci blocking
This is expensive but I'm not sure if the more reasonable  "/payload-aggregate periodic-ci-openshift-release-master-ci-4.20-upgrade-from-stable-4.19-e2e-aws-ovn-upgrade 10" actually runs these standard deviation tests, it might...
> OCPBUGS-58158: Enable watch termination grace period

- .ci-operator.yaml
- Dockerfile.rhel7
- go.mod
- pkg/operator/kubeletversionskewcontroller/kubelet_version_skew_controller_test.go
- test/e2e/serviceaccountissuer_test.go
What does the PR do?
1. Updated go version to 1.24 and ocp version to 4.20
2. Updated go version in go.mod and go mod tidy && go mod vendor && go mod verify
3. Fixed below unit test error,
```
pkg/operator/kubeletversionskewcontroller/kubelet_version_skew_controller_test.go:176:12: non-constant format string in call to (*testing.common).Logf
```
4. Fixed make verify error,
```
$ make verify
Running `gofmt -s -l` on 137 file(s).
go vet -mod=vendor ./...
test/e2e/serviceaccountissuer_test.go:33:13: non-constant format string in call to (*testing.common).Errorf
test/e2e/serviceaccountissuer_test.go:40:13: non-constant format string in call to (*testing.common).Errorf
test/e2e/serviceaccountissuer_test.go:47:13: non-constant format string in call to (*testing.common).Errorf
```
> OCPBUGS-57811: Updating ose-cluster-kube-apiserver-operator-container image to be consistent with ART for 4.20

- pkg/cmd/certregenerationcontroller/cmd.go
Reverts openshift/cluster-kube-apiserver-operator#1861
Investigating [TRT-2190](https://issues.redhat.com/browse/TRT-2190) gcp minor upgrade failures due to pathological events like
```
event happened 25 times, something is wrong: namespace/openshift-kube-apiserver hmsg/cf99229525 - reason/SecretUpdated Updated Secret/kube-controller-manager-client-cert-key -n openshift-config-managed because it changed (05:57:30Z) result=reject 
```
> Revert "[release-4.19] OCPBUGS-58116: certregenerationcontroller: start configInformers again"

- bindata/assets/alerts/api-usage.yaml
OpenShift 4.20 is an EUS release based on Kubernetes 1.33, so the EUS alert needs to fire for Kubernetes 1.34 and 1.35 removals.
> NO-JIRA: Update the deprecated API usage alerts for 1.33.

- bindata/assets/kube-apiserver/svc.yaml
Add ports 6080 (insecure-readyz) and 17697 (check-endpoints) to the apiserver service. These ports were already exposed by the pods but missing from the service definition, preventing EndpointSlice creation for communication matrix documentation (for mor details see [bug](https://issues.redhat.com/browse/OCPBUGS-50489) description)
> OCPBUGS-50489: Add missing service ports to apiserver service

- go.mod
- go.sum
- pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller.go
- pkg/operator/nodekubeconfigcontroller/nodekubeconfigcontroller_test.go
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go
- vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go
- vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
- vendor/modules.txt
Pull in https://github.com/openshift/library-go/pull/1971 to make sure most secrets created by controller would have refresh-period annotation set.
> OCPBUGS-44842: Set not-before/not-after annotations

- pkg/operator/certrotationcontroller/certrotationcontroller.go
This signer is used to issue the certificate for node-system-admin-client. The target certificate is expected to last 2 years, however it cannot be valid longer than its signer. As a result, signer validity is extended to 3 years, being refreshed at 80% of its lifetime (2.5 years)
This change is required to test [1 year shutdowns](https://github.com/openshift/release/pull/64965) (instead of just 360d)
> OCPBUGS-59527: certrotationcontroller: extend node-system-admin-signer lifetime

- pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
Instead of re-creating configmap from scratch every time this function should attempt to use existing configmap and replace the contents only. This would prevent extra configmap updates when metadata changes.
Bump library-go to update https://github.com/openshift/library-go/pull/1936
> OCPBUGS-55217: Optimistically update Kube Server and Client CA bundles

- bindata/assets/config/defaultconfig.yaml
- pkg/cmd/render/render.go
- pkg/operator/configobservation/apiserver/observe_goaway_chance.go
- pkg/operator/configobservation/apiserver/observe_goaway_chance_test.go
- pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
Backport PR https://github.com/openshift/cluster-kube-apiserver-operator/pull/1863 to release-4.19 manually.
> OCPBUGS-60121: [release-4.19] Set goaway chance to 0.001
